// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/account_invite_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_account_invite_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_account_invite_service_proto_rawDesc = "" +
	"\n" +
	"(api/auth/v1/account_invite_service.proto\x12\fgh.protos.v1\x1a api/auth/v1/account_invite.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\xa7\x01\n" +
	"\x14AccountInviteService\x12\x8e\x01\n" +
	"\x13InviteUserToAccount\x12(.gh.protos.v1.InviteUserToAccountRequest\x1a).gh.protos.v1.InviteUserToAccountResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/account_invitesB\xc1\x01\n" +
	"\x10com.gh.protos.v1B\x19AccountInviteServiceProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_account_invite_service_proto_goTypes = []any{
	(*InviteUserToAccountRequest)(nil),  // 0: gh.protos.v1.InviteUserToAccountRequest
	(*InviteUserToAccountResponse)(nil), // 1: gh.protos.v1.InviteUserToAccountResponse
}
var file_api_auth_v1_account_invite_service_proto_depIdxs = []int32{
	0, // 0: gh.protos.v1.AccountInviteService.InviteUserToAccount:input_type -> gh.protos.v1.InviteUserToAccountRequest
	1, // 1: gh.protos.v1.AccountInviteService.InviteUserToAccount:output_type -> gh.protos.v1.InviteUserToAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_account_invite_service_proto_init() }
func file_api_auth_v1_account_invite_service_proto_init() {
	if File_api_auth_v1_account_invite_service_proto != nil {
		return
	}
	file_api_auth_v1_account_invite_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_account_invite_service_proto_rawDesc), len(file_api_auth_v1_account_invite_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_account_invite_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_account_invite_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_account_invite_service_proto = out.File
	file_api_auth_v1_account_invite_service_proto_goTypes = nil
	file_api_auth_v1_account_invite_service_proto_depIdxs = nil
}
