// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/account.proto

package protosv1

import (
	v1 "github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Number         string                 `protobuf:"bytes,5,opt,name=number,proto3" json:"number,omitempty"`
	DialCode       string                 `protobuf:"bytes,6,opt,name=dial_code,json=dialCode,proto3" json:"dial_code,omitempty"`
	Email          string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	IsVerified     bool                   `protobuf:"varint,8,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	UserId         string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsSignup       bool                   `protobuf:"varint,10,opt,name=is_signup,json=isSignup,proto3" json:"is_signup,omitempty"`
	Username       string                 `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`
	AdminUser      bool                   `protobuf:"varint,12,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateAccountRequest) GetDialCode() string {
	if x != nil {
		return x.DialCode
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetIsSignup() bool {
	if x != nil {
		return x.IsSignup
	}
	return false
}

func (x *CreateAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAccountRequest) GetAdminUser() bool {
	if x != nil {
		return x.AdminUser
	}
	return false
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber  string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Currency       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DialCode       string                 `protobuf:"bytes,6,opt,name=dial_code,json=dialCode,proto3" json:"dial_code,omitempty"`
	Number         string                 `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	Email          string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Status         AuthStatus             `protobuf:"varint,9,opt,name=status,proto3,enum=gh.protos.v1.AuthStatus" json:"status,omitempty"`
	CountryCode    string                 `protobuf:"bytes,10,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	IsVerified     bool                   `protobuf:"varint,11,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Balance        float64                `protobuf:"fixed64,12,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatorId      string                 `protobuf:"bytes,13,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ApiKey         string                 `protobuf:"bytes,14,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	HourlyRate     float64                `protobuf:"fixed64,15,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	IsCardApproved bool                   `protobuf:"varint,16,opt,name=is_card_approved,json=isCardApproved,proto3" json:"is_card_approved,omitempty"`
	Web3PrivateKey string                 `protobuf:"bytes,17,opt,name=web3_private_key,json=web3PrivateKey,proto3" json:"web3_private_key,omitempty"`
	Uuid           string                 `protobuf:"bytes,18,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IsRegistration bool                   `protobuf:"varint,19,opt,name=is_registration,json=isRegistration,proto3" json:"is_registration,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id             string                 `protobuf:"bytes,21,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_auth_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetDialCode() string {
	if x != nil {
		return x.DialCode
	}
	return ""
}

func (x *Account) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetStatus() AuthStatus {
	if x != nil {
		return x.Status
	}
	return AuthStatus_UNKNOWN
}

func (x *Account) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Account) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Account) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Account) GetHourlyRate() float64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *Account) GetIsCardApproved() bool {
	if x != nil {
		return x.IsCardApproved
	}
	return false
}

func (x *Account) GetWeb3PrivateKey() string {
	if x != nil {
		return x.Web3PrivateKey
	}
	return ""
}

func (x *Account) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Account) GetIsRegistration() bool {
	if x != nil {
		return x.IsRegistration
	}
	return false
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountByIDRequest) Reset() {
	*x = AccountByIDRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountByIDRequest) ProtoMessage() {}

func (x *AccountByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountByIDRequest.ProtoReflect.Descriptor instead.
func (*AccountByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountByIDRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountByIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type AccountByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountByIDResponse) Reset() {
	*x = AccountByIDResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountByIDResponse) ProtoMessage() {}

func (x *AccountByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountByIDResponse.ProtoReflect.Descriptor instead.
func (*AccountByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountByIDResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountByUUIDRequest) Reset() {
	*x = AccountByUUIDRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountByUUIDRequest) ProtoMessage() {}

func (x *AccountByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountByUUIDRequest.ProtoReflect.Descriptor instead.
func (*AccountByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *AccountByUUIDRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type AccountByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountByUUIDResponse) Reset() {
	*x = AccountByUUIDResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountByUUIDResponse) ProtoMessage() {}

func (x *AccountByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountByUUIDResponse.ProtoReflect.Descriptor instead.
func (*AccountByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *AccountByUUIDResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountsForOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page           int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Per            int64                  `protobuf:"varint,3,opt,name=per,proto3" json:"per,omitempty"`
	Term           string                 `protobuf:"bytes,4,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountsForOrganizationRequest) Reset() {
	*x = AccountsForOrganizationRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsForOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsForOrganizationRequest) ProtoMessage() {}

func (x *AccountsForOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsForOrganizationRequest.ProtoReflect.Descriptor instead.
func (*AccountsForOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *AccountsForOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AccountsForOrganizationRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AccountsForOrganizationRequest) GetPer() int64 {
	if x != nil {
		return x.Per
	}
	return 0
}

func (x *AccountsForOrganizationRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type AccountsForOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsForOrganizationResponse) Reset() {
	*x = AccountsForOrganizationResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsForOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsForOrganizationResponse) ProtoMessage() {}

func (x *AccountsForOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsForOrganizationResponse.ProtoReflect.Descriptor instead.
func (*AccountsForOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *AccountsForOrganizationResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountsForOrganizationResponse) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AccountsForUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page           int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Per            int64                  `protobuf:"varint,3,opt,name=per,proto3" json:"per,omitempty"`
	Term           string                 `protobuf:"bytes,4,opt,name=term,proto3" json:"term,omitempty"`
	UserId         string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountsForUserRequest) Reset() {
	*x = AccountsForUserRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsForUserRequest) ProtoMessage() {}

func (x *AccountsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsForUserRequest.ProtoReflect.Descriptor instead.
func (*AccountsForUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *AccountsForUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AccountsForUserRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AccountsForUserRequest) GetPer() int64 {
	if x != nil {
		return x.Per
	}
	return 0
}

func (x *AccountsForUserRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *AccountsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccountsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsForUserResponse) Reset() {
	*x = AccountsForUserResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsForUserResponse) ProtoMessage() {}

func (x *AccountsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsForUserResponse.ProtoReflect.Descriptor instead.
func (*AccountsForUserResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *AccountsForUserResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountsForUserResponse) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AccountByPhoneNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountByPhoneNumberRequest) Reset() {
	*x = AccountByPhoneNumberRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountByPhoneNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountByPhoneNumberRequest) ProtoMessage() {}

func (x *AccountByPhoneNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountByPhoneNumberRequest.ProtoReflect.Descriptor instead.
func (*AccountByPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *AccountByPhoneNumberRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type AccountByPhoneNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountByPhoneNumberResponse) Reset() {
	*x = AccountByPhoneNumberResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountByPhoneNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountByPhoneNumberResponse) ProtoMessage() {}

func (x *AccountByPhoneNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountByPhoneNumberResponse.ProtoReflect.Descriptor instead.
func (*AccountByPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *AccountByPhoneNumberResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountsRequest) Reset() {
	*x = AccountsRequest{}
	mi := &file_api_auth_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsRequest) ProtoMessage() {}

func (x *AccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsRequest.ProtoReflect.Descriptor instead.
func (*AccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *AccountsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type AccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsResponse) Reset() {
	*x = AccountsResponse{}
	mi := &file_api_auth_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsResponse) ProtoMessage() {}

func (x *AccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsResponse.ProtoReflect.Descriptor instead.
func (*AccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *AccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_api_auth_v1_account_proto protoreflect.FileDescriptor

const file_api_auth_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x19api/auth/v1/account.proto\x12\fgh.protos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dapi/auth/v1/auth_status.proto\x1a\x1eapi/common/v1/pagination.proto\"\xee\x02\n" +
	"\x14CreateAccountRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06number\x18\x05 \x01(\tR\x06number\x12\x1b\n" +
	"\tdial_code\x18\x06 \x01(\tR\bdialCode\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x1f\n" +
	"\vis_verified\x18\b \x01(\bR\n" +
	"isVerified\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_signup\x18\n" +
	" \x01(\bR\bisSignup\x12\x1a\n" +
	"\busername\x18\v \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"admin_user\x18\f \x01(\bR\tadminUser\"\xf6\x05\n" +
	"\aAccount\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tdial_code\x18\x06 \x01(\tR\bdialCode\x12\x16\n" +
	"\x06number\x18\a \x01(\tR\x06number\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x120\n" +
	"\x06status\x18\t \x01(\x0e2\x18.gh.protos.v1.AuthStatusR\x06status\x12!\n" +
	"\fcountry_code\x18\n" +
	" \x01(\tR\vcountryCode\x12\x1f\n" +
	"\vis_verified\x18\v \x01(\bR\n" +
	"isVerified\x12\x18\n" +
	"\abalance\x18\f \x01(\x01R\abalance\x12\x1d\n" +
	"\n" +
	"creator_id\x18\r \x01(\tR\tcreatorId\x12\x17\n" +
	"\aapi_key\x18\x0e \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vhourly_rate\x18\x0f \x01(\x01R\n" +
	"hourlyRate\x12(\n" +
	"\x10is_card_approved\x18\x10 \x01(\bR\x0eisCardApproved\x12(\n" +
	"\x10web3_private_key\x18\x11 \x01(\tR\x0eweb3PrivateKey\x12\x12\n" +
	"\x04uuid\x18\x12 \x01(\tR\x04uuid\x12'\n" +
	"\x0fis_registration\x18\x13 \x01(\bR\x0eisRegistration\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x0e\n" +
	"\x02id\x18\x15 \x01(\tR\x02id\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"H\n" +
	"\x15CreateAccountResponse\x12/\n" +
	"\aaccount\x18\x01 \x01(\v2\x15.gh.protos.v1.AccountR\aaccount\"G\n" +
	"\x12AccountByIDRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"F\n" +
	"\x13AccountByIDResponse\x12/\n" +
	"\aaccount\x18\x01 \x01(\v2\x15.gh.protos.v1.AccountR\aaccount\"I\n" +
	"\x14AccountByUUIDRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"H\n" +
	"\x15AccountByUUIDResponse\x12/\n" +
	"\aaccount\x18\x01 \x01(\v2\x15.gh.protos.v1.AccountR\aaccount\"\x83\x01\n" +
	"\x1eAccountsForOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x10\n" +
	"\x03per\x18\x03 \x01(\x03R\x03per\x12\x12\n" +
	"\x04term\x18\x04 \x01(\tR\x04term\"\x8e\x01\n" +
	"\x1fAccountsForOrganizationResponse\x121\n" +
	"\baccounts\x18\x01 \x03(\v2\x15.gh.protos.v1.AccountR\baccounts\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.gh.common.v1.PaginationR\n" +
	"pagination\"\x94\x01\n" +
	"\x16AccountsForUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x10\n" +
	"\x03per\x18\x03 \x01(\x03R\x03per\x12\x12\n" +
	"\x04term\x18\x04 \x01(\tR\x04term\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"\x86\x01\n" +
	"\x17AccountsForUserResponse\x121\n" +
	"\baccounts\x18\x01 \x03(\v2\x15.gh.protos.v1.AccountR\baccounts\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.gh.common.v1.PaginationR\n" +
	"pagination\"@\n" +
	"\x1bAccountByPhoneNumberRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"O\n" +
	"\x1cAccountByPhoneNumberResponse\x12/\n" +
	"\aaccount\x18\x01 \x01(\v2\x15.gh.protos.v1.AccountR\aaccount\":\n" +
	"\x0fAccountsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"E\n" +
	"\x10AccountsResponse\x121\n" +
	"\baccounts\x18\x01 \x03(\v2\x15.gh.protos.v1.AccountR\baccountsB\xb4\x01\n" +
	"\x10com.gh.protos.v1B\fAccountProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_account_proto_rawDescOnce sync.Once
	file_api_auth_v1_account_proto_rawDescData []byte
)

func file_api_auth_v1_account_proto_rawDescGZIP() []byte {
	file_api_auth_v1_account_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_account_proto_rawDesc), len(file_api_auth_v1_account_proto_rawDesc)))
	})
	return file_api_auth_v1_account_proto_rawDescData
}

var file_api_auth_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_auth_v1_account_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),            // 0: gh.protos.v1.CreateAccountRequest
	(*Account)(nil),                         // 1: gh.protos.v1.Account
	(*CreateAccountResponse)(nil),           // 2: gh.protos.v1.CreateAccountResponse
	(*AccountByIDRequest)(nil),              // 3: gh.protos.v1.AccountByIDRequest
	(*AccountByIDResponse)(nil),             // 4: gh.protos.v1.AccountByIDResponse
	(*AccountByUUIDRequest)(nil),            // 5: gh.protos.v1.AccountByUUIDRequest
	(*AccountByUUIDResponse)(nil),           // 6: gh.protos.v1.AccountByUUIDResponse
	(*AccountsForOrganizationRequest)(nil),  // 7: gh.protos.v1.AccountsForOrganizationRequest
	(*AccountsForOrganizationResponse)(nil), // 8: gh.protos.v1.AccountsForOrganizationResponse
	(*AccountsForUserRequest)(nil),          // 9: gh.protos.v1.AccountsForUserRequest
	(*AccountsForUserResponse)(nil),         // 10: gh.protos.v1.AccountsForUserResponse
	(*AccountByPhoneNumberRequest)(nil),     // 11: gh.protos.v1.AccountByPhoneNumberRequest
	(*AccountByPhoneNumberResponse)(nil),    // 12: gh.protos.v1.AccountByPhoneNumberResponse
	(*AccountsRequest)(nil),                 // 13: gh.protos.v1.AccountsRequest
	(*AccountsResponse)(nil),                // 14: gh.protos.v1.AccountsResponse
	(AuthStatus)(0),                         // 15: gh.protos.v1.AuthStatus
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
	(*v1.Pagination)(nil),                   // 17: gh.common.v1.Pagination
}
var file_api_auth_v1_account_proto_depIdxs = []int32{
	15, // 0: gh.protos.v1.Account.status:type_name -> gh.protos.v1.AuthStatus
	16, // 1: gh.protos.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: gh.protos.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: gh.protos.v1.CreateAccountResponse.account:type_name -> gh.protos.v1.Account
	1,  // 4: gh.protos.v1.AccountByIDResponse.account:type_name -> gh.protos.v1.Account
	1,  // 5: gh.protos.v1.AccountByUUIDResponse.account:type_name -> gh.protos.v1.Account
	1,  // 6: gh.protos.v1.AccountsForOrganizationResponse.accounts:type_name -> gh.protos.v1.Account
	17, // 7: gh.protos.v1.AccountsForOrganizationResponse.pagination:type_name -> gh.common.v1.Pagination
	1,  // 8: gh.protos.v1.AccountsForUserResponse.accounts:type_name -> gh.protos.v1.Account
	17, // 9: gh.protos.v1.AccountsForUserResponse.pagination:type_name -> gh.common.v1.Pagination
	1,  // 10: gh.protos.v1.AccountByPhoneNumberResponse.account:type_name -> gh.protos.v1.Account
	1,  // 11: gh.protos.v1.AccountsResponse.accounts:type_name -> gh.protos.v1.Account
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_auth_v1_account_proto_init() }
func file_api_auth_v1_account_proto_init() {
	if File_api_auth_v1_account_proto != nil {
		return
	}
	file_api_auth_v1_auth_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_account_proto_rawDesc), len(file_api_auth_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_account_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_account_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_account_proto_msgTypes,
	}.Build()
	File_api_auth_v1_account_proto = out.File
	file_api_auth_v1_account_proto_goTypes = nil
	file_api_auth_v1_account_proto_depIdxs = nil
}
