// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/account_invite.proto

package protosv1

import (
	_ "github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteUserToAccountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccountId          string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email              string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId     string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PhoneNumber        string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	BaseUrl            string                 `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	AssignedAccountIds []string               `protobuf:"bytes,7,rep,name=assigned_account_ids,json=assignedAccountIds,proto3" json:"assigned_account_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InviteUserToAccountRequest) Reset() {
	*x = InviteUserToAccountRequest{}
	mi := &file_api_auth_v1_account_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserToAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserToAccountRequest) ProtoMessage() {}

func (x *InviteUserToAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserToAccountRequest.ProtoReflect.Descriptor instead.
func (*InviteUserToAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_invite_proto_rawDescGZIP(), []int{0}
}

func (x *InviteUserToAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *InviteUserToAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteUserToAccountRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *InviteUserToAccountRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *InviteUserToAccountRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *InviteUserToAccountRequest) GetAssignedAccountIds() []string {
	if x != nil {
		return x.AssignedAccountIds
	}
	return nil
}

type InviteUserToAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserToAccountResponse) Reset() {
	*x = InviteUserToAccountResponse{}
	mi := &file_api_auth_v1_account_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserToAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserToAccountResponse) ProtoMessage() {}

func (x *InviteUserToAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_account_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserToAccountResponse.ProtoReflect.Descriptor instead.
func (*InviteUserToAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_account_invite_proto_rawDescGZIP(), []int{1}
}

func (x *InviteUserToAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_auth_v1_account_invite_proto protoreflect.FileDescriptor

const file_api_auth_v1_account_invite_proto_rawDesc = "" +
	"\n" +
	" api/auth/v1/account_invite.proto\x12\fgh.protos.v1\x1a api/common/v1/phone_number.proto\"\xea\x01\n" +
	"\x1aInviteUserToAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\x120\n" +
	"\x14assigned_account_ids\x18\a \x03(\tR\x12assignedAccountIds\"7\n" +
	"\x1bInviteUserToAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\xba\x01\n" +
	"\x10com.gh.protos.v1B\x12AccountInviteProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_account_invite_proto_rawDescOnce sync.Once
	file_api_auth_v1_account_invite_proto_rawDescData []byte
)

func file_api_auth_v1_account_invite_proto_rawDescGZIP() []byte {
	file_api_auth_v1_account_invite_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_account_invite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_account_invite_proto_rawDesc), len(file_api_auth_v1_account_invite_proto_rawDesc)))
	})
	return file_api_auth_v1_account_invite_proto_rawDescData
}

var file_api_auth_v1_account_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_auth_v1_account_invite_proto_goTypes = []any{
	(*InviteUserToAccountRequest)(nil),  // 0: gh.protos.v1.InviteUserToAccountRequest
	(*InviteUserToAccountResponse)(nil), // 1: gh.protos.v1.InviteUserToAccountResponse
}
var file_api_auth_v1_account_invite_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_account_invite_proto_init() }
func file_api_auth_v1_account_invite_proto_init() {
	if File_api_auth_v1_account_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_account_invite_proto_rawDesc), len(file_api_auth_v1_account_invite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_account_invite_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_account_invite_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_account_invite_proto_msgTypes,
	}.Build()
	File_api_auth_v1_account_invite_proto = out.File
	file_api_auth_v1_account_invite_proto_goTypes = nil
	file_api_auth_v1_account_invite_proto_depIdxs = nil
}
