// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/account_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_account_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_account_service_proto_rawDesc = "" +
	"\n" +
	"!api/auth/v1/account_service.proto\x12\fgh.protos.v1\x1a\x19api/auth/v1/account.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\x8d\a\n" +
	"\x0eAccountService\x12\x85\x01\n" +
	"\vAccountByID\x12 .gh.protos.v1.AccountByIDRequest\x1a!.gh.protos.v1.AccountByIDResponse\"1\xdaA\n" +
	"account_id\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/account/{account_id}\x12\xb4\x01\n" +
	"\x14AccountByPhoneNumber\x12).gh.protos.v1.AccountByPhoneNumberRequest\x1a*.gh.protos.v1.AccountByPhoneNumberResponse\"E\xdaA\fphone_number\x82\xd3\xe4\x93\x020\x12./api/v1/account_by_phone_number/{phone_number}\x12\x87\x01\n" +
	"\rAccountByUUID\x12\".gh.protos.v1.AccountByUUIDRequest\x1a#.gh.protos.v1.AccountByUUIDResponse\"-\xdaA\x04uuid\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/account/{uuid}/profile\x12\xb0\x01\n" +
	"\x17AccountsForOrganization\x12,.gh.protos.v1.AccountsForOrganizationRequest\x1a-.gh.protos.v1.AccountsForOrganizationResponse\"8\x82\xd3\xe4\x93\x022\x120/api/v1/organizations/{organization_id}/accounts\x12\x87\x01\n" +
	"\x0fAccountsForUser\x12$.gh.protos.v1.AccountsForUserRequest\x1a%.gh.protos.v1.AccountsForUserResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/user/{user_id}/accounts\x12u\n" +
	"\rCreateAccount\x12\".gh.protos.v1.CreateAccountRequest\x1a#.gh.protos.v1.CreateAccountResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/accountsB\xbb\x01\n" +
	"\x10com.gh.protos.v1B\x13AccountServiceProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_account_service_proto_goTypes = []any{
	(*AccountByIDRequest)(nil),              // 0: gh.protos.v1.AccountByIDRequest
	(*AccountByPhoneNumberRequest)(nil),     // 1: gh.protos.v1.AccountByPhoneNumberRequest
	(*AccountByUUIDRequest)(nil),            // 2: gh.protos.v1.AccountByUUIDRequest
	(*AccountsForOrganizationRequest)(nil),  // 3: gh.protos.v1.AccountsForOrganizationRequest
	(*AccountsForUserRequest)(nil),          // 4: gh.protos.v1.AccountsForUserRequest
	(*CreateAccountRequest)(nil),            // 5: gh.protos.v1.CreateAccountRequest
	(*AccountByIDResponse)(nil),             // 6: gh.protos.v1.AccountByIDResponse
	(*AccountByPhoneNumberResponse)(nil),    // 7: gh.protos.v1.AccountByPhoneNumberResponse
	(*AccountByUUIDResponse)(nil),           // 8: gh.protos.v1.AccountByUUIDResponse
	(*AccountsForOrganizationResponse)(nil), // 9: gh.protos.v1.AccountsForOrganizationResponse
	(*AccountsForUserResponse)(nil),         // 10: gh.protos.v1.AccountsForUserResponse
	(*CreateAccountResponse)(nil),           // 11: gh.protos.v1.CreateAccountResponse
}
var file_api_auth_v1_account_service_proto_depIdxs = []int32{
	0,  // 0: gh.protos.v1.AccountService.AccountByID:input_type -> gh.protos.v1.AccountByIDRequest
	1,  // 1: gh.protos.v1.AccountService.AccountByPhoneNumber:input_type -> gh.protos.v1.AccountByPhoneNumberRequest
	2,  // 2: gh.protos.v1.AccountService.AccountByUUID:input_type -> gh.protos.v1.AccountByUUIDRequest
	3,  // 3: gh.protos.v1.AccountService.AccountsForOrganization:input_type -> gh.protos.v1.AccountsForOrganizationRequest
	4,  // 4: gh.protos.v1.AccountService.AccountsForUser:input_type -> gh.protos.v1.AccountsForUserRequest
	5,  // 5: gh.protos.v1.AccountService.CreateAccount:input_type -> gh.protos.v1.CreateAccountRequest
	6,  // 6: gh.protos.v1.AccountService.AccountByID:output_type -> gh.protos.v1.AccountByIDResponse
	7,  // 7: gh.protos.v1.AccountService.AccountByPhoneNumber:output_type -> gh.protos.v1.AccountByPhoneNumberResponse
	8,  // 8: gh.protos.v1.AccountService.AccountByUUID:output_type -> gh.protos.v1.AccountByUUIDResponse
	9,  // 9: gh.protos.v1.AccountService.AccountsForOrganization:output_type -> gh.protos.v1.AccountsForOrganizationResponse
	10, // 10: gh.protos.v1.AccountService.AccountsForUser:output_type -> gh.protos.v1.AccountsForUserResponse
	11, // 11: gh.protos.v1.AccountService.CreateAccount:output_type -> gh.protos.v1.CreateAccountResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_account_service_proto_init() }
func file_api_auth_v1_account_service_proto_init() {
	if File_api_auth_v1_account_service_proto != nil {
		return
	}
	file_api_auth_v1_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_account_service_proto_rawDesc), len(file_api_auth_v1_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_account_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_account_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_account_service_proto = out.File
	file_api_auth_v1_account_service_proto_goTypes = nil
	file_api_auth_v1_account_service_proto_depIdxs = nil
}
