// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/auth/v1/account_service.proto

package protosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_AccountByID_FullMethodName             = "/gh.protos.v1.AccountService/AccountByID"
	AccountService_AccountByPhoneNumber_FullMethodName    = "/gh.protos.v1.AccountService/AccountByPhoneNumber"
	AccountService_AccountByUUID_FullMethodName           = "/gh.protos.v1.AccountService/AccountByUUID"
	AccountService_AccountsForOrganization_FullMethodName = "/gh.protos.v1.AccountService/AccountsForOrganization"
	AccountService_AccountsForUser_FullMethodName         = "/gh.protos.v1.AccountService/AccountsForUser"
	AccountService_CreateAccount_FullMethodName           = "/gh.protos.v1.AccountService/CreateAccount"
	AccountService_Accounts_FullMethodName                = "/gh.protos.v1.AccountService/Accounts"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	// AccountByID fetches an account by id
	AccountByID(ctx context.Context, in *AccountByIDRequest, opts ...grpc.CallOption) (*AccountByIDResponse, error)
	// AccountByPhoneNumber account by a given phone number
	AccountByPhoneNumber(ctx context.Context, in *AccountByPhoneNumberRequest, opts ...grpc.CallOption) (*AccountByPhoneNumberResponse, error)
	// AccountByUUID gets an account profile
	AccountByUUID(ctx context.Context, in *AccountByUUIDRequest, opts ...grpc.CallOption) (*AccountByUUIDResponse, error)
	// AccountsForOrganization get organizations for an organization
	AccountsForOrganization(ctx context.Context, in *AccountsForOrganizationRequest, opts ...grpc.CallOption) (*AccountsForOrganizationResponse, error)
	// AccountsForUser returns accounts that a user belongs to
	AccountsForUser(ctx context.Context, in *AccountsForUserRequest, opts ...grpc.CallOption) (*AccountsForUserResponse, error)
	// CreateAccount create a new account for an organization
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// AccountsForUser returns accounts that a user belongs to
	Accounts(ctx context.Context, in *AccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AccountByID(ctx context.Context, in *AccountByIDRequest, opts ...grpc.CallOption) (*AccountByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountByIDResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AccountByPhoneNumber(ctx context.Context, in *AccountByPhoneNumberRequest, opts ...grpc.CallOption) (*AccountByPhoneNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountByPhoneNumberResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountByPhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AccountByUUID(ctx context.Context, in *AccountByUUIDRequest, opts ...grpc.CallOption) (*AccountByUUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountByUUIDResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountByUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AccountsForOrganization(ctx context.Context, in *AccountsForOrganizationRequest, opts ...grpc.CallOption) (*AccountsForOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountsForOrganizationResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountsForOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AccountsForUser(ctx context.Context, in *AccountsForUserRequest, opts ...grpc.CallOption) (*AccountsForUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountsForUserResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountsForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Accounts(ctx context.Context, in *AccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_Accounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
type AccountServiceServer interface {
	// AccountByID fetches an account by id
	AccountByID(context.Context, *AccountByIDRequest) (*AccountByIDResponse, error)
	// AccountByPhoneNumber account by a given phone number
	AccountByPhoneNumber(context.Context, *AccountByPhoneNumberRequest) (*AccountByPhoneNumberResponse, error)
	// AccountByUUID gets an account profile
	AccountByUUID(context.Context, *AccountByUUIDRequest) (*AccountByUUIDResponse, error)
	// AccountsForOrganization get organizations for an organization
	AccountsForOrganization(context.Context, *AccountsForOrganizationRequest) (*AccountsForOrganizationResponse, error)
	// AccountsForUser returns accounts that a user belongs to
	AccountsForUser(context.Context, *AccountsForUserRequest) (*AccountsForUserResponse, error)
	// CreateAccount create a new account for an organization
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// AccountsForUser returns accounts that a user belongs to
	Accounts(context.Context, *AccountsRequest) (*AccountsResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) AccountByID(context.Context, *AccountByIDRequest) (*AccountByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountByID not implemented")
}
func (UnimplementedAccountServiceServer) AccountByPhoneNumber(context.Context, *AccountByPhoneNumberRequest) (*AccountByPhoneNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountByPhoneNumber not implemented")
}
func (UnimplementedAccountServiceServer) AccountByUUID(context.Context, *AccountByUUIDRequest) (*AccountByUUIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountByUUID not implemented")
}
func (UnimplementedAccountServiceServer) AccountsForOrganization(context.Context, *AccountsForOrganizationRequest) (*AccountsForOrganizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountsForOrganization not implemented")
}
func (UnimplementedAccountServiceServer) AccountsForUser(context.Context, *AccountsForUserRequest) (*AccountsForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountsForUser not implemented")
}
func (UnimplementedAccountServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountServiceServer) Accounts(context.Context, *AccountsRequest) (*AccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accounts not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_AccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountByID(ctx, req.(*AccountByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AccountByPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountByPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountByPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountByPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountByPhoneNumber(ctx, req.(*AccountByPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AccountByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountByUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountByUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountByUUID(ctx, req.(*AccountByUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AccountsForOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsForOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountsForOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountsForOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountsForOrganization(ctx, req.(*AccountsForOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AccountsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountsForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountsForUser(ctx, req.(*AccountsForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Accounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Accounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Accounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Accounts(ctx, req.(*AccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gh.protos.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountByID",
			Handler:    _AccountService_AccountByID_Handler,
		},
		{
			MethodName: "AccountByPhoneNumber",
			Handler:    _AccountService_AccountByPhoneNumber_Handler,
		},
		{
			MethodName: "AccountByUUID",
			Handler:    _AccountService_AccountByUUID_Handler,
		},
		{
			MethodName: "AccountsForOrganization",
			Handler:    _AccountService_AccountsForOrganization_Handler,
		},
		{
			MethodName: "AccountsForUser",
			Handler:    _AccountService_AccountsForUser_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "Accounts",
			Handler:    _AccountService_Accounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/v1/account_service.proto",
}
