// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/api_key.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAPIKeyRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ValidateAPIKeyRequest) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

type APIKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,6,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{2}
}

func (x *APIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKey) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *APIKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKey) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *APIKey) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type APIKeyByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyByUsernameRequest) Reset() {
	*x = APIKeyByUsernameRequest{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyByUsernameRequest) ProtoMessage() {}

func (x *APIKeyByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyByUsernameRequest.ProtoReflect.Descriptor instead.
func (*APIKeyByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{3}
}

func (x *APIKeyByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type APIKeyByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyByUsernameResponse) Reset() {
	*x = APIKeyByUsernameResponse{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyByUsernameResponse) ProtoMessage() {}

func (x *APIKeyByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyByUsernameResponse.ProtoReflect.Descriptor instead.
func (*APIKeyByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{4}
}

func (x *APIKeyByUsernameResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_api_auth_v1_api_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_api_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_api_key_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

var File_api_auth_v1_api_key_proto protoreflect.FileDescriptor

const file_api_auth_v1_api_key_proto_rawDesc = "" +
	"\n" +
	"\x19api/auth/v1/api_key.proto\x12\fgh.protos.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"H\n" +
	"\x13CreateAPIKeyRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\"\xbb\x01\n" +
	"\x06APIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x06 \x01(\tR\tapiSecret\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"5\n" +
	"\x17APIKeyByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\x18APIKeyByUsernameResponse\x12-\n" +
	"\aapi_key\x18\x01 \x01(\v2\x14.gh.protos.v1.APIKeyR\x06apiKey\"E\n" +
	"\x14CreateAPIKeyResponse\x12-\n" +
	"\aapi_key\x18\x01 \x01(\v2\x14.gh.protos.v1.APIKeyR\x06apiKey\"G\n" +
	"\x16ValidateAPIKeyResponse\x12-\n" +
	"\aapi_key\x18\x01 \x01(\v2\x14.gh.protos.v1.APIKeyR\x06apiKeyB\xb3\x01\n" +
	"\x10com.gh.protos.v1B\vApiKeyProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_api_key_proto_rawDescOnce sync.Once
	file_api_auth_v1_api_key_proto_rawDescData []byte
)

func file_api_auth_v1_api_key_proto_rawDescGZIP() []byte {
	file_api_auth_v1_api_key_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_api_key_proto_rawDesc), len(file_api_auth_v1_api_key_proto_rawDesc)))
	})
	return file_api_auth_v1_api_key_proto_rawDescData
}

var file_api_auth_v1_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_auth_v1_api_key_proto_goTypes = []any{
	(*CreateAPIKeyRequest)(nil),      // 0: gh.protos.v1.CreateAPIKeyRequest
	(*ValidateAPIKeyRequest)(nil),    // 1: gh.protos.v1.ValidateAPIKeyRequest
	(*APIKey)(nil),                   // 2: gh.protos.v1.APIKey
	(*APIKeyByUsernameRequest)(nil),  // 3: gh.protos.v1.APIKeyByUsernameRequest
	(*APIKeyByUsernameResponse)(nil), // 4: gh.protos.v1.APIKeyByUsernameResponse
	(*CreateAPIKeyResponse)(nil),     // 5: gh.protos.v1.CreateAPIKeyResponse
	(*ValidateAPIKeyResponse)(nil),   // 6: gh.protos.v1.ValidateAPIKeyResponse
}
var file_api_auth_v1_api_key_proto_depIdxs = []int32{
	2, // 0: gh.protos.v1.APIKeyByUsernameResponse.api_key:type_name -> gh.protos.v1.APIKey
	2, // 1: gh.protos.v1.CreateAPIKeyResponse.api_key:type_name -> gh.protos.v1.APIKey
	2, // 2: gh.protos.v1.ValidateAPIKeyResponse.api_key:type_name -> gh.protos.v1.APIKey
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_auth_v1_api_key_proto_init() }
func file_api_auth_v1_api_key_proto_init() {
	if File_api_auth_v1_api_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_api_key_proto_rawDesc), len(file_api_auth_v1_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_api_key_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_api_key_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_api_key_proto_msgTypes,
	}.Build()
	File_api_auth_v1_api_key_proto = out.File
	file_api_auth_v1_api_key_proto_goTypes = nil
	file_api_auth_v1_api_key_proto_depIdxs = nil
}
