// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/api_key_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_api_key_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_api_key_service_proto_rawDesc = "" +
	"\n" +
	"!api/auth/v1/api_key_service.proto\x12\fgh.protos.v1\x1a\x19api/auth/v1/api_key.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\x9b\x03\n" +
	"\rAPIKeyService\x12\x91\x01\n" +
	"\x10APIKeyByUsername\x12%.gh.protos.v1.APIKeyByUsernameRequest\x1a&.gh.protos.v1.APIKeyByUsernameResponse\".\xdaA\busername\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/api_keys/{username}\x12r\n" +
	"\fCreateAPIKey\x12!.gh.protos.v1.CreateAPIKeyRequest\x1a\".gh.protos.v1.CreateAPIKeyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/api_keys\x12\x81\x01\n" +
	"\x0eValidateAPIKey\x12#.gh.protos.v1.ValidateAPIKeyRequest\x1a$.gh.protos.v1.ValidateAPIKeyResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/api_keys/validateB\xc5\x01\n" +
	"\x10com.gh.protos.v1B\x12ApiKeyServiceProtoP\x01ZKgithub.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_api_key_service_proto_goTypes = []any{
	(*APIKeyByUsernameRequest)(nil),  // 0: gh.protos.v1.APIKeyByUsernameRequest
	(*CreateAPIKeyRequest)(nil),      // 1: gh.protos.v1.CreateAPIKeyRequest
	(*ValidateAPIKeyRequest)(nil),    // 2: gh.protos.v1.ValidateAPIKeyRequest
	(*APIKeyByUsernameResponse)(nil), // 3: gh.protos.v1.APIKeyByUsernameResponse
	(*CreateAPIKeyResponse)(nil),     // 4: gh.protos.v1.CreateAPIKeyResponse
	(*ValidateAPIKeyResponse)(nil),   // 5: gh.protos.v1.ValidateAPIKeyResponse
}
var file_api_auth_v1_api_key_service_proto_depIdxs = []int32{
	0, // 0: gh.protos.v1.APIKeyService.APIKeyByUsername:input_type -> gh.protos.v1.APIKeyByUsernameRequest
	1, // 1: gh.protos.v1.APIKeyService.CreateAPIKey:input_type -> gh.protos.v1.CreateAPIKeyRequest
	2, // 2: gh.protos.v1.APIKeyService.ValidateAPIKey:input_type -> gh.protos.v1.ValidateAPIKeyRequest
	3, // 3: gh.protos.v1.APIKeyService.APIKeyByUsername:output_type -> gh.protos.v1.APIKeyByUsernameResponse
	4, // 4: gh.protos.v1.APIKeyService.CreateAPIKey:output_type -> gh.protos.v1.CreateAPIKeyResponse
	5, // 5: gh.protos.v1.APIKeyService.ValidateAPIKey:output_type -> gh.protos.v1.ValidateAPIKeyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_api_key_service_proto_init() }
func file_api_auth_v1_api_key_service_proto_init() {
	if File_api_auth_v1_api_key_service_proto != nil {
		return
	}
	file_api_auth_v1_api_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_api_key_service_proto_rawDesc), len(file_api_auth_v1_api_key_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_api_key_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_api_key_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_api_key_service_proto = out.File
	file_api_auth_v1_api_key_service_proto_goTypes = nil
	file_api_auth_v1_api_key_service_proto_depIdxs = nil
}
