// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/auth_status.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthStatus int32

const (
	AuthStatus_UNKNOWN  AuthStatus = 0
	AuthStatus_inactive AuthStatus = 1
	AuthStatus_verified AuthStatus = 2
	AuthStatus_pending  AuthStatus = 3
	AuthStatus_banned   AuthStatus = 4
	AuthStatus_active   AuthStatus = 5
)

// Enum value maps for AuthStatus.
var (
	AuthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "inactive",
		2: "verified",
		3: "pending",
		4: "banned",
		5: "active",
	}
	AuthStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"inactive": 1,
		"verified": 2,
		"pending":  3,
		"banned":   4,
		"active":   5,
	}
)

func (x AuthStatus) Enum() *AuthStatus {
	p := new(AuthStatus)
	*p = x
	return p
}

func (x AuthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_auth_status_proto_enumTypes[0].Descriptor()
}

func (AuthStatus) Type() protoreflect.EnumType {
	return &file_api_auth_v1_auth_status_proto_enumTypes[0]
}

func (x AuthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStatus.Descriptor instead.
func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_status_proto_rawDescGZIP(), []int{0}
}

var File_api_auth_v1_auth_status_proto protoreflect.FileDescriptor

const file_api_auth_v1_auth_status_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/auth/v1/auth_status.proto\x12\fgh.protos.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto*Z\n" +
	"\n" +
	"AuthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\binactive\x10\x01\x12\f\n" +
	"\bverified\x10\x02\x12\v\n" +
	"\apending\x10\x03\x12\n" +
	"\n" +
	"\x06banned\x10\x04\x12\n" +
	"\n" +
	"\x06active\x10\x05B\xc2\x01\n" +
	"\x10com.gh.protos.v1B\x0fAuthStatusProtoP\x01ZKgithub.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_auth_status_proto_rawDescOnce sync.Once
	file_api_auth_v1_auth_status_proto_rawDescData []byte
)

func file_api_auth_v1_auth_status_proto_rawDescGZIP() []byte {
	file_api_auth_v1_auth_status_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_auth_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_status_proto_rawDesc), len(file_api_auth_v1_auth_status_proto_rawDesc)))
	})
	return file_api_auth_v1_auth_status_proto_rawDescData
}

var file_api_auth_v1_auth_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_auth_v1_auth_status_proto_goTypes = []any{
	(AuthStatus)(0), // 0: gh.protos.v1.AuthStatus
}
var file_api_auth_v1_auth_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_auth_status_proto_init() }
func file_api_auth_v1_auth_status_proto_init() {
	if File_api_auth_v1_auth_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_status_proto_rawDesc), len(file_api_auth_v1_auth_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_auth_status_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_auth_status_proto_depIdxs,
		EnumInfos:         file_api_auth_v1_auth_status_proto_enumTypes,
	}.Build()
	File_api_auth_v1_auth_status_proto = out.File
	file_api_auth_v1_auth_status_proto_goTypes = nil
	file_api_auth_v1_auth_status_proto_depIdxs = nil
}
