// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/kyc.proto

package protosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KYCStatus int32

const (
	KYCStatus_KYC_STATUS_UNSPECIFIED KYCStatus = 0
	KYCStatus_KYC_STATUS_PENDING     KYCStatus = 1
	KYCStatus_KYC_STATUS_ACCEPTED    KYCStatus = 2
	KYCStatus_KYC_STATUS_REJECTED    KYCStatus = 3
)

// Enum value maps for KYCStatus.
var (
	KYCStatus_name = map[int32]string{
		0: "KYC_STATUS_UNSPECIFIED",
		1: "KYC_STATUS_PENDING",
		2: "KYC_STATUS_ACCEPTED",
		3: "KYC_STATUS_REJECTED",
	}
	KYCStatus_value = map[string]int32{
		"KYC_STATUS_UNSPECIFIED": 0,
		"KYC_STATUS_PENDING":     1,
		"KYC_STATUS_ACCEPTED":    2,
		"KYC_STATUS_REJECTED":    3,
	}
)

func (x KYCStatus) Enum() *KYCStatus {
	p := new(KYCStatus)
	*p = x
	return p
}

func (x KYCStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KYCStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_kyc_proto_enumTypes[0].Descriptor()
}

func (KYCStatus) Type() protoreflect.EnumType {
	return &file_api_auth_v1_kyc_proto_enumTypes[0]
}

func (x KYCStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KYCStatus.Descriptor instead.
func (KYCStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{0}
}

type KYCSubmission struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Id                  string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID string
	UserType            string                  `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	FirstName           string                  `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName            string                  `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	NationalId          string                  `protobuf:"bytes,5,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	DateOfBirth         *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	BusinessDescription *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"`
	TaxDocumentNumber   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=tax_document_number,json=taxDocumentNumber,proto3" json:"tax_document_number,omitempty"`
	DocumentType        string                  `protobuf:"bytes,9,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DirectorNames       *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=director_names,json=directorNames,proto3" json:"director_names,omitempty"`
	PhoneNumber         string                  `protobuf:"bytes,11,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email               string                  `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	IdFront             string                  `protobuf:"bytes,13,opt,name=id_front,json=idFront,proto3" json:"id_front,omitempty"`
	IdBack              string                  `protobuf:"bytes,14,opt,name=id_back,json=idBack,proto3" json:"id_back,omitempty"`
	ProofOfAddress      string                  `protobuf:"bytes,15,opt,name=proof_of_address,json=proofOfAddress,proto3" json:"proof_of_address,omitempty"`
	BusinessRegCert     *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=business_reg_cert,json=businessRegCert,proto3" json:"business_reg_cert,omitempty"`
	Cr12                *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=cr12,proto3" json:"cr12,omitempty"`
	TaxDocument         *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=tax_document,json=taxDocument,proto3" json:"tax_document,omitempty"`
	Status              KYCStatus               `protobuf:"varint,19,opt,name=status,proto3,enum=gh.protos.v1.KYCStatus" json:"status,omitempty"`
	Notes               *wrapperspb.StringValue `protobuf:"bytes,20,opt,name=notes,proto3" json:"notes,omitempty"`
	AccountId           string                  `protobuf:"bytes,21,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreatedAt           *timestamppb.Timestamp  `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp  `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Country             string                  `protobuf:"bytes,24,opt,name=country,proto3" json:"country,omitempty"`
	Address             string                  `protobuf:"bytes,25,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *KYCSubmission) Reset() {
	*x = KYCSubmission{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCSubmission) ProtoMessage() {}

func (x *KYCSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCSubmission.ProtoReflect.Descriptor instead.
func (*KYCSubmission) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *KYCSubmission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KYCSubmission) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *KYCSubmission) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *KYCSubmission) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *KYCSubmission) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *KYCSubmission) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *KYCSubmission) GetBusinessDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.BusinessDescription
	}
	return nil
}

func (x *KYCSubmission) GetTaxDocumentNumber() *wrapperspb.StringValue {
	if x != nil {
		return x.TaxDocumentNumber
	}
	return nil
}

func (x *KYCSubmission) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *KYCSubmission) GetDirectorNames() *wrapperspb.StringValue {
	if x != nil {
		return x.DirectorNames
	}
	return nil
}

func (x *KYCSubmission) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *KYCSubmission) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *KYCSubmission) GetIdFront() string {
	if x != nil {
		return x.IdFront
	}
	return ""
}

func (x *KYCSubmission) GetIdBack() string {
	if x != nil {
		return x.IdBack
	}
	return ""
}

func (x *KYCSubmission) GetProofOfAddress() string {
	if x != nil {
		return x.ProofOfAddress
	}
	return ""
}

func (x *KYCSubmission) GetBusinessRegCert() *wrapperspb.StringValue {
	if x != nil {
		return x.BusinessRegCert
	}
	return nil
}

func (x *KYCSubmission) GetCr12() *wrapperspb.StringValue {
	if x != nil {
		return x.Cr12
	}
	return nil
}

func (x *KYCSubmission) GetTaxDocument() *wrapperspb.StringValue {
	if x != nil {
		return x.TaxDocument
	}
	return nil
}

func (x *KYCSubmission) GetStatus() KYCStatus {
	if x != nil {
		return x.Status
	}
	return KYCStatus_KYC_STATUS_UNSPECIFIED
}

func (x *KYCSubmission) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *KYCSubmission) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *KYCSubmission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KYCSubmission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KYCSubmission) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *KYCSubmission) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *KYCSubmission         `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKYCRequest) Reset() {
	*x = CreateKYCRequest{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKYCRequest) ProtoMessage() {}

func (x *CreateKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKYCRequest.ProtoReflect.Descriptor instead.
func (*CreateKYCRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKYCRequest) GetSubmission() *KYCSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type CreateKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *KYCSubmission         `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKYCResponse) Reset() {
	*x = CreateKYCResponse{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKYCResponse) ProtoMessage() {}

func (x *CreateKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKYCResponse.ProtoReflect.Descriptor instead.
func (*CreateKYCResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKYCResponse) GetSubmission() *KYCSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetKYCByPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCByPhoneRequest) Reset() {
	*x = GetKYCByPhoneRequest{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCByPhoneRequest) ProtoMessage() {}

func (x *GetKYCByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetKYCByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{3}
}

func (x *GetKYCByPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetKYCByPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *KYCSubmission         `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCByPhoneResponse) Reset() {
	*x = GetKYCByPhoneResponse{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCByPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCByPhoneResponse) ProtoMessage() {}

func (x *GetKYCByPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCByPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetKYCByPhoneResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{4}
}

func (x *GetKYCByPhoneResponse) GetSubmission() *KYCSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetKYCByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCByIDRequest) Reset() {
	*x = GetKYCByIDRequest{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCByIDRequest) ProtoMessage() {}

func (x *GetKYCByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCByIDRequest.ProtoReflect.Descriptor instead.
func (*GetKYCByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{5}
}

func (x *GetKYCByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetKYCByAccountIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCByAccountIDRequest) Reset() {
	*x = GetKYCByAccountIDRequest{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCByAccountIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCByAccountIDRequest) ProtoMessage() {}

func (x *GetKYCByAccountIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCByAccountIDRequest.ProtoReflect.Descriptor instead.
func (*GetKYCByAccountIDRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{6}
}

func (x *GetKYCByAccountIDRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetKYCByAccountIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *KYCSubmission         `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCByAccountIDResponse) Reset() {
	*x = GetKYCByAccountIDResponse{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCByAccountIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCByAccountIDResponse) ProtoMessage() {}

func (x *GetKYCByAccountIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCByAccountIDResponse.ProtoReflect.Descriptor instead.
func (*GetKYCByAccountIDResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{7}
}

func (x *GetKYCByAccountIDResponse) GetSubmission() *KYCSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetKYCByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *KYCSubmission         `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCByIDResponse) Reset() {
	*x = GetKYCByIDResponse{}
	mi := &file_api_auth_v1_kyc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCByIDResponse) ProtoMessage() {}

func (x *GetKYCByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_kyc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCByIDResponse.ProtoReflect.Descriptor instead.
func (*GetKYCByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_kyc_proto_rawDescGZIP(), []int{8}
}

func (x *GetKYCByIDResponse) GetSubmission() *KYCSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

var File_api_auth_v1_kyc_proto protoreflect.FileDescriptor

const file_api_auth_v1_kyc_proto_rawDesc = "" +
	"\n" +
	"\x15api/auth/v1/kyc.proto\x12\fgh.protos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe4\b\n" +
	"\rKYCSubmission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_type\x18\x02 \x01(\tR\buserType\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vnational_id\x18\x05 \x01(\tR\n" +
	"nationalId\x12>\n" +
	"\rdate_of_birth\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12O\n" +
	"\x14business_description\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x13businessDescription\x12L\n" +
	"\x13tax_document_number\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x11taxDocumentNumber\x12#\n" +
	"\rdocument_type\x18\t \x01(\tR\fdocumentType\x12C\n" +
	"\x0edirector_names\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\rdirectorNames\x12!\n" +
	"\fphone_number\x18\v \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\x12\x19\n" +
	"\bid_front\x18\r \x01(\tR\aidFront\x12\x17\n" +
	"\aid_back\x18\x0e \x01(\tR\x06idBack\x12(\n" +
	"\x10proof_of_address\x18\x0f \x01(\tR\x0eproofOfAddress\x12H\n" +
	"\x11business_reg_cert\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\x0fbusinessRegCert\x120\n" +
	"\x04cr12\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\x04cr12\x12?\n" +
	"\ftax_document\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\vtaxDocument\x12/\n" +
	"\x06status\x18\x13 \x01(\x0e2\x17.gh.protos.v1.KYCStatusR\x06status\x122\n" +
	"\x05notes\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12\x1d\n" +
	"\n" +
	"account_id\x18\x15 \x01(\tR\taccountId\x129\n" +
	"\n" +
	"created_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\acountry\x18\x18 \x01(\tR\acountry\x12\x18\n" +
	"\aaddress\x18\x19 \x01(\tR\aaddress\"O\n" +
	"\x10CreateKYCRequest\x12;\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x1b.gh.protos.v1.KYCSubmissionR\n" +
	"submission\"P\n" +
	"\x11CreateKYCResponse\x12;\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x1b.gh.protos.v1.KYCSubmissionR\n" +
	"submission\"9\n" +
	"\x14GetKYCByPhoneRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"T\n" +
	"\x15GetKYCByPhoneResponse\x12;\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x1b.gh.protos.v1.KYCSubmissionR\n" +
	"submission\"#\n" +
	"\x11GetKYCByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x18GetKYCByAccountIDRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"X\n" +
	"\x19GetKYCByAccountIDResponse\x12;\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x1b.gh.protos.v1.KYCSubmissionR\n" +
	"submission\"Q\n" +
	"\x12GetKYCByIDResponse\x12;\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x1b.gh.protos.v1.KYCSubmissionR\n" +
	"submission*q\n" +
	"\tKYCStatus\x12\x1a\n" +
	"\x16KYC_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KYC_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13KYC_STATUS_ACCEPTED\x10\x02\x12\x17\n" +
	"\x13KYC_STATUS_REJECTED\x10\x03B\xb0\x01\n" +
	"\x10com.gh.protos.v1B\bKycProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_kyc_proto_rawDescOnce sync.Once
	file_api_auth_v1_kyc_proto_rawDescData []byte
)

func file_api_auth_v1_kyc_proto_rawDescGZIP() []byte {
	file_api_auth_v1_kyc_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_kyc_proto_rawDesc), len(file_api_auth_v1_kyc_proto_rawDesc)))
	})
	return file_api_auth_v1_kyc_proto_rawDescData
}

var file_api_auth_v1_kyc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_auth_v1_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_auth_v1_kyc_proto_goTypes = []any{
	(KYCStatus)(0),                    // 0: gh.protos.v1.KYCStatus
	(*KYCSubmission)(nil),             // 1: gh.protos.v1.KYCSubmission
	(*CreateKYCRequest)(nil),          // 2: gh.protos.v1.CreateKYCRequest
	(*CreateKYCResponse)(nil),         // 3: gh.protos.v1.CreateKYCResponse
	(*GetKYCByPhoneRequest)(nil),      // 4: gh.protos.v1.GetKYCByPhoneRequest
	(*GetKYCByPhoneResponse)(nil),     // 5: gh.protos.v1.GetKYCByPhoneResponse
	(*GetKYCByIDRequest)(nil),         // 6: gh.protos.v1.GetKYCByIDRequest
	(*GetKYCByAccountIDRequest)(nil),  // 7: gh.protos.v1.GetKYCByAccountIDRequest
	(*GetKYCByAccountIDResponse)(nil), // 8: gh.protos.v1.GetKYCByAccountIDResponse
	(*GetKYCByIDResponse)(nil),        // 9: gh.protos.v1.GetKYCByIDResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),    // 11: google.protobuf.StringValue
}
var file_api_auth_v1_kyc_proto_depIdxs = []int32{
	10, // 0: gh.protos.v1.KYCSubmission.date_of_birth:type_name -> google.protobuf.Timestamp
	11, // 1: gh.protos.v1.KYCSubmission.business_description:type_name -> google.protobuf.StringValue
	11, // 2: gh.protos.v1.KYCSubmission.tax_document_number:type_name -> google.protobuf.StringValue
	11, // 3: gh.protos.v1.KYCSubmission.director_names:type_name -> google.protobuf.StringValue
	11, // 4: gh.protos.v1.KYCSubmission.business_reg_cert:type_name -> google.protobuf.StringValue
	11, // 5: gh.protos.v1.KYCSubmission.cr12:type_name -> google.protobuf.StringValue
	11, // 6: gh.protos.v1.KYCSubmission.tax_document:type_name -> google.protobuf.StringValue
	0,  // 7: gh.protos.v1.KYCSubmission.status:type_name -> gh.protos.v1.KYCStatus
	11, // 8: gh.protos.v1.KYCSubmission.notes:type_name -> google.protobuf.StringValue
	10, // 9: gh.protos.v1.KYCSubmission.created_at:type_name -> google.protobuf.Timestamp
	10, // 10: gh.protos.v1.KYCSubmission.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: gh.protos.v1.CreateKYCRequest.submission:type_name -> gh.protos.v1.KYCSubmission
	1,  // 12: gh.protos.v1.CreateKYCResponse.submission:type_name -> gh.protos.v1.KYCSubmission
	1,  // 13: gh.protos.v1.GetKYCByPhoneResponse.submission:type_name -> gh.protos.v1.KYCSubmission
	1,  // 14: gh.protos.v1.GetKYCByAccountIDResponse.submission:type_name -> gh.protos.v1.KYCSubmission
	1,  // 15: gh.protos.v1.GetKYCByIDResponse.submission:type_name -> gh.protos.v1.KYCSubmission
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_auth_v1_kyc_proto_init() }
func file_api_auth_v1_kyc_proto_init() {
	if File_api_auth_v1_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_kyc_proto_rawDesc), len(file_api_auth_v1_kyc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_kyc_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_kyc_proto_depIdxs,
		EnumInfos:         file_api_auth_v1_kyc_proto_enumTypes,
		MessageInfos:      file_api_auth_v1_kyc_proto_msgTypes,
	}.Build()
	File_api_auth_v1_kyc_proto = out.File
	file_api_auth_v1_kyc_proto_goTypes = nil
	file_api_auth_v1_kyc_proto_depIdxs = nil
}
