// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/kyc_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_kyc_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_kyc_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/auth/v1/kyc_service.proto\x12\fgh.protos.v1\x1a\x15api/auth/v1/kyc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\x91\x04\n" +
	"\n" +
	"KYCService\x12d\n" +
	"\tCreateKYC\x12\x1e.gh.protos.v1.CreateKYCRequest\x1a\x1f.gh.protos.v1.CreateKYCResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/kyc\x12\x8b\x01\n" +
	"\rGetKYCByPhone\x12\".gh.protos.v1.GetKYCByPhoneRequest\x1a#.gh.protos.v1.GetKYCByPhoneResponse\"1\xdaA\fphone_number\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/kyc/{phone_number}\x12n\n" +
	"\n" +
	"GetKYCByID\x12\x1f.gh.protos.v1.GetKYCByIDRequest\x1a .gh.protos.v1.GetKYCByIDResponse\"\x1d\xdaA\x02id\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/kyc/{id}\x12\x9e\x01\n" +
	"\x11GetKYCByAccountID\x12&.gh.protos.v1.GetKYCByAccountIDRequest\x1a'.gh.protos.v1.GetKYCByAccountIDResponse\"8\xdaA\n" +
	"account_id\x82\xd3\xe4\x93\x02%\x12#/api/v1/kyc_by_account/{account_id}B\xb7\x01\n" +
	"\x10com.gh.protos.v1B\x0fKycServiceProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_kyc_service_proto_goTypes = []any{
	(*CreateKYCRequest)(nil),          // 0: gh.protos.v1.CreateKYCRequest
	(*GetKYCByPhoneRequest)(nil),      // 1: gh.protos.v1.GetKYCByPhoneRequest
	(*GetKYCByIDRequest)(nil),         // 2: gh.protos.v1.GetKYCByIDRequest
	(*GetKYCByAccountIDRequest)(nil),  // 3: gh.protos.v1.GetKYCByAccountIDRequest
	(*CreateKYCResponse)(nil),         // 4: gh.protos.v1.CreateKYCResponse
	(*GetKYCByPhoneResponse)(nil),     // 5: gh.protos.v1.GetKYCByPhoneResponse
	(*GetKYCByIDResponse)(nil),        // 6: gh.protos.v1.GetKYCByIDResponse
	(*GetKYCByAccountIDResponse)(nil), // 7: gh.protos.v1.GetKYCByAccountIDResponse
}
var file_api_auth_v1_kyc_service_proto_depIdxs = []int32{
	0, // 0: gh.protos.v1.KYCService.CreateKYC:input_type -> gh.protos.v1.CreateKYCRequest
	1, // 1: gh.protos.v1.KYCService.GetKYCByPhone:input_type -> gh.protos.v1.GetKYCByPhoneRequest
	2, // 2: gh.protos.v1.KYCService.GetKYCByID:input_type -> gh.protos.v1.GetKYCByIDRequest
	3, // 3: gh.protos.v1.KYCService.GetKYCByAccountID:input_type -> gh.protos.v1.GetKYCByAccountIDRequest
	4, // 4: gh.protos.v1.KYCService.CreateKYC:output_type -> gh.protos.v1.CreateKYCResponse
	5, // 5: gh.protos.v1.KYCService.GetKYCByPhone:output_type -> gh.protos.v1.GetKYCByPhoneResponse
	6, // 6: gh.protos.v1.KYCService.GetKYCByID:output_type -> gh.protos.v1.GetKYCByIDResponse
	7, // 7: gh.protos.v1.KYCService.GetKYCByAccountID:output_type -> gh.protos.v1.GetKYCByAccountIDResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_kyc_service_proto_init() }
func file_api_auth_v1_kyc_service_proto_init() {
	if File_api_auth_v1_kyc_service_proto != nil {
		return
	}
	file_api_auth_v1_kyc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_kyc_service_proto_rawDesc), len(file_api_auth_v1_kyc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_kyc_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_kyc_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_kyc_service_proto = out.File
	file_api_auth_v1_kyc_service_proto_goTypes = nil
	file_api_auth_v1_kyc_service_proto_depIdxs = nil
}
