// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/auth/v1/kyc_service.proto

package protosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KYCService_CreateKYC_FullMethodName         = "/gh.protos.v1.KYCService/CreateKYC"
	KYCService_GetKYCByPhone_FullMethodName     = "/gh.protos.v1.KYCService/GetKYCByPhone"
	KYCService_GetKYCByID_FullMethodName        = "/gh.protos.v1.KYCService/GetKYCByID"
	KYCService_GetKYCByAccountID_FullMethodName = "/gh.protos.v1.KYCService/GetKYCByAccountID"
)

// KYCServiceClient is the client API for KYCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KYCServiceClient interface {
	CreateKYC(ctx context.Context, in *CreateKYCRequest, opts ...grpc.CallOption) (*CreateKYCResponse, error)
	GetKYCByPhone(ctx context.Context, in *GetKYCByPhoneRequest, opts ...grpc.CallOption) (*GetKYCByPhoneResponse, error)
	GetKYCByID(ctx context.Context, in *GetKYCByIDRequest, opts ...grpc.CallOption) (*GetKYCByIDResponse, error)
	GetKYCByAccountID(ctx context.Context, in *GetKYCByAccountIDRequest, opts ...grpc.CallOption) (*GetKYCByAccountIDResponse, error)
}

type kYCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKYCServiceClient(cc grpc.ClientConnInterface) KYCServiceClient {
	return &kYCServiceClient{cc}
}

func (c *kYCServiceClient) CreateKYC(ctx context.Context, in *CreateKYCRequest, opts ...grpc.CallOption) (*CreateKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKYCResponse)
	err := c.cc.Invoke(ctx, KYCService_CreateKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kYCServiceClient) GetKYCByPhone(ctx context.Context, in *GetKYCByPhoneRequest, opts ...grpc.CallOption) (*GetKYCByPhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCByPhoneResponse)
	err := c.cc.Invoke(ctx, KYCService_GetKYCByPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kYCServiceClient) GetKYCByID(ctx context.Context, in *GetKYCByIDRequest, opts ...grpc.CallOption) (*GetKYCByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCByIDResponse)
	err := c.cc.Invoke(ctx, KYCService_GetKYCByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kYCServiceClient) GetKYCByAccountID(ctx context.Context, in *GetKYCByAccountIDRequest, opts ...grpc.CallOption) (*GetKYCByAccountIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCByAccountIDResponse)
	err := c.cc.Invoke(ctx, KYCService_GetKYCByAccountID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KYCServiceServer is the server API for KYCService service.
// All implementations must embed UnimplementedKYCServiceServer
// for forward compatibility.
type KYCServiceServer interface {
	CreateKYC(context.Context, *CreateKYCRequest) (*CreateKYCResponse, error)
	GetKYCByPhone(context.Context, *GetKYCByPhoneRequest) (*GetKYCByPhoneResponse, error)
	GetKYCByID(context.Context, *GetKYCByIDRequest) (*GetKYCByIDResponse, error)
	GetKYCByAccountID(context.Context, *GetKYCByAccountIDRequest) (*GetKYCByAccountIDResponse, error)
	mustEmbedUnimplementedKYCServiceServer()
}

// UnimplementedKYCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKYCServiceServer struct{}

func (UnimplementedKYCServiceServer) CreateKYC(context.Context, *CreateKYCRequest) (*CreateKYCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKYC not implemented")
}
func (UnimplementedKYCServiceServer) GetKYCByPhone(context.Context, *GetKYCByPhoneRequest) (*GetKYCByPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKYCByPhone not implemented")
}
func (UnimplementedKYCServiceServer) GetKYCByID(context.Context, *GetKYCByIDRequest) (*GetKYCByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKYCByID not implemented")
}
func (UnimplementedKYCServiceServer) GetKYCByAccountID(context.Context, *GetKYCByAccountIDRequest) (*GetKYCByAccountIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKYCByAccountID not implemented")
}
func (UnimplementedKYCServiceServer) mustEmbedUnimplementedKYCServiceServer() {}
func (UnimplementedKYCServiceServer) testEmbeddedByValue()                    {}

// UnsafeKYCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KYCServiceServer will
// result in compilation errors.
type UnsafeKYCServiceServer interface {
	mustEmbedUnimplementedKYCServiceServer()
}

func RegisterKYCServiceServer(s grpc.ServiceRegistrar, srv KYCServiceServer) {
	// If the following call pancis, it indicates UnimplementedKYCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KYCService_ServiceDesc, srv)
}

func _KYCService_CreateKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).CreateKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_CreateKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).CreateKYC(ctx, req.(*CreateKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KYCService_GetKYCByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).GetKYCByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_GetKYCByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).GetKYCByPhone(ctx, req.(*GetKYCByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KYCService_GetKYCByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).GetKYCByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_GetKYCByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).GetKYCByID(ctx, req.(*GetKYCByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KYCService_GetKYCByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCByAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServiceServer).GetKYCByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCService_GetKYCByAccountID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServiceServer).GetKYCByAccountID(ctx, req.(*GetKYCByAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KYCService_ServiceDesc is the grpc.ServiceDesc for KYCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KYCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gh.protos.v1.KYCService",
	HandlerType: (*KYCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKYC",
			Handler:    _KYCService_CreateKYC_Handler,
		},
		{
			MethodName: "GetKYCByPhone",
			Handler:    _KYCService_GetKYCByPhone_Handler,
		},
		{
			MethodName: "GetKYCByID",
			Handler:    _KYCService_GetKYCByID_Handler,
		},
		{
			MethodName: "GetKYCByAccountID",
			Handler:    _KYCService_GetKYCByAccountID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/v1/kyc_service.proto",
}
