// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/auth/v1/organization_service.proto

package protosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrganizationService_OrganizationByID_FullMethodName     = "/gh.protos.v1.OrganizationService/OrganizationByID"
	OrganizationService_OrganizationByOwner_FullMethodName  = "/gh.protos.v1.OrganizationService/OrganizationByOwner"
	OrganizationService_OrganizationsForUser_FullMethodName = "/gh.protos.v1.OrganizationService/OrganizationsForUser"
)

// OrganizationServiceClient is the client API for OrganizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrganizationServiceClient interface {
	OrganizationByID(ctx context.Context, in *OrganizationByIDRequest, opts ...grpc.CallOption) (*OrganizationByIDResponse, error)
	OrganizationByOwner(ctx context.Context, in *OrganizationByOwnerRequest, opts ...grpc.CallOption) (*OrganizationByOwnerResponse, error)
	OrganizationsForUser(ctx context.Context, in *OrganizationsForUserRequest, opts ...grpc.CallOption) (*OrganizationsForUserResponse, error)
}

type organizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizationServiceClient(cc grpc.ClientConnInterface) OrganizationServiceClient {
	return &organizationServiceClient{cc}
}

func (c *organizationServiceClient) OrganizationByID(ctx context.Context, in *OrganizationByIDRequest, opts ...grpc.CallOption) (*OrganizationByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationByIDResponse)
	err := c.cc.Invoke(ctx, OrganizationService_OrganizationByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) OrganizationByOwner(ctx context.Context, in *OrganizationByOwnerRequest, opts ...grpc.CallOption) (*OrganizationByOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationByOwnerResponse)
	err := c.cc.Invoke(ctx, OrganizationService_OrganizationByOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) OrganizationsForUser(ctx context.Context, in *OrganizationsForUserRequest, opts ...grpc.CallOption) (*OrganizationsForUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsForUserResponse)
	err := c.cc.Invoke(ctx, OrganizationService_OrganizationsForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationServiceServer is the server API for OrganizationService service.
// All implementations must embed UnimplementedOrganizationServiceServer
// for forward compatibility.
type OrganizationServiceServer interface {
	OrganizationByID(context.Context, *OrganizationByIDRequest) (*OrganizationByIDResponse, error)
	OrganizationByOwner(context.Context, *OrganizationByOwnerRequest) (*OrganizationByOwnerResponse, error)
	OrganizationsForUser(context.Context, *OrganizationsForUserRequest) (*OrganizationsForUserResponse, error)
	mustEmbedUnimplementedOrganizationServiceServer()
}

// UnimplementedOrganizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrganizationServiceServer struct{}

func (UnimplementedOrganizationServiceServer) OrganizationByID(context.Context, *OrganizationByIDRequest) (*OrganizationByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrganizationByID not implemented")
}
func (UnimplementedOrganizationServiceServer) OrganizationByOwner(context.Context, *OrganizationByOwnerRequest) (*OrganizationByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrganizationByOwner not implemented")
}
func (UnimplementedOrganizationServiceServer) OrganizationsForUser(context.Context, *OrganizationsForUserRequest) (*OrganizationsForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrganizationsForUser not implemented")
}
func (UnimplementedOrganizationServiceServer) mustEmbedUnimplementedOrganizationServiceServer() {}
func (UnimplementedOrganizationServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrganizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrganizationServiceServer will
// result in compilation errors.
type UnsafeOrganizationServiceServer interface {
	mustEmbedUnimplementedOrganizationServiceServer()
}

func RegisterOrganizationServiceServer(s grpc.ServiceRegistrar, srv OrganizationServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrganizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrganizationService_ServiceDesc, srv)
}

func _OrganizationService_OrganizationByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).OrganizationByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_OrganizationByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).OrganizationByID(ctx, req.(*OrganizationByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_OrganizationByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).OrganizationByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_OrganizationByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).OrganizationByOwner(ctx, req.(*OrganizationByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_OrganizationsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).OrganizationsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationService_OrganizationsForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).OrganizationsForUser(ctx, req.(*OrganizationsForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrganizationService_ServiceDesc is the grpc.ServiceDesc for OrganizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrganizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gh.protos.v1.OrganizationService",
	HandlerType: (*OrganizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrganizationByID",
			Handler:    _OrganizationService_OrganizationByID_Handler,
		},
		{
			MethodName: "OrganizationByOwner",
			Handler:    _OrganizationService_OrganizationByOwner_Handler,
		},
		{
			MethodName: "OrganizationsForUser",
			Handler:    _OrganizationService_OrganizationsForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/v1/organization_service.proto",
}
