// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/organization_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_organization_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_organization_service_proto_rawDesc = "" +
	"\n" +
	"&api/auth/v1/organization_service.proto\x12\fgh.protos.v1\x1a\x1eapi/auth/v1/organization.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\xf1\x03\n" +
	"\x13OrganizationService\x12\x8a\x01\n" +
	"\x10OrganizationByID\x12%.gh.protos.v1.OrganizationByIDRequest\x1a&.gh.protos.v1.OrganizationByIDResponse\"'\xdaA\x02id\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/organizations/{id}\x12\xa3\x01\n" +
	"\x13OrganizationByOwner\x12(.gh.protos.v1.OrganizationByOwnerRequest\x1a).gh.protos.v1.OrganizationByOwnerResponse\"7\xdaA\auser_id\x82\xd3\xe4\x93\x02'\x12%/api/v1/organizations/{user_id}/owner\x12\xa6\x01\n" +
	"\x14OrganizationsForUser\x12).gh.protos.v1.OrganizationsForUserRequest\x1a*.gh.protos.v1.OrganizationsForUserResponse\"7\xdaA\auser_id\x82\xd3\xe4\x93\x02'\x12%/api/v1/users/{user_id}/organizationsB\xcb\x01\n" +
	"\x10com.gh.protos.v1B\x18OrganizationServiceProtoP\x01ZKgithub.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_organization_service_proto_goTypes = []any{
	(*OrganizationByIDRequest)(nil),      // 0: gh.protos.v1.OrganizationByIDRequest
	(*OrganizationByOwnerRequest)(nil),   // 1: gh.protos.v1.OrganizationByOwnerRequest
	(*OrganizationsForUserRequest)(nil),  // 2: gh.protos.v1.OrganizationsForUserRequest
	(*OrganizationByIDResponse)(nil),     // 3: gh.protos.v1.OrganizationByIDResponse
	(*OrganizationByOwnerResponse)(nil),  // 4: gh.protos.v1.OrganizationByOwnerResponse
	(*OrganizationsForUserResponse)(nil), // 5: gh.protos.v1.OrganizationsForUserResponse
}
var file_api_auth_v1_organization_service_proto_depIdxs = []int32{
	0, // 0: gh.protos.v1.OrganizationService.OrganizationByID:input_type -> gh.protos.v1.OrganizationByIDRequest
	1, // 1: gh.protos.v1.OrganizationService.OrganizationByOwner:input_type -> gh.protos.v1.OrganizationByOwnerRequest
	2, // 2: gh.protos.v1.OrganizationService.OrganizationsForUser:input_type -> gh.protos.v1.OrganizationsForUserRequest
	3, // 3: gh.protos.v1.OrganizationService.OrganizationByID:output_type -> gh.protos.v1.OrganizationByIDResponse
	4, // 4: gh.protos.v1.OrganizationService.OrganizationByOwner:output_type -> gh.protos.v1.OrganizationByOwnerResponse
	5, // 5: gh.protos.v1.OrganizationService.OrganizationsForUser:output_type -> gh.protos.v1.OrganizationsForUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_organization_service_proto_init() }
func file_api_auth_v1_organization_service_proto_init() {
	if File_api_auth_v1_organization_service_proto != nil {
		return
	}
	file_api_auth_v1_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_organization_service_proto_rawDesc), len(file_api_auth_v1_organization_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_organization_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_organization_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_organization_service_proto = out.File
	file_api_auth_v1_organization_service_proto_goTypes = nil
	file_api_auth_v1_organization_service_proto_depIdxs = nil
}
