// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/organization.proto

package protosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Organization_OrganizationType int32

const (
	Organization_UNKNOWN    Organization_OrganizationType = 0
	Organization_individual Organization_OrganizationType = 1
	Organization_business   Organization_OrganizationType = 2
)

// Enum value maps for Organization_OrganizationType.
var (
	Organization_OrganizationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "individual",
		2: "business",
	}
	Organization_OrganizationType_value = map[string]int32{
		"UNKNOWN":    0,
		"individual": 1,
		"business":   2,
	}
)

func (x Organization_OrganizationType) Enum() *Organization_OrganizationType {
	p := new(Organization_OrganizationType)
	*p = x
	return p
}

func (x Organization_OrganizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Organization_OrganizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_organization_proto_enumTypes[0].Descriptor()
}

func (Organization_OrganizationType) Type() protoreflect.EnumType {
	return &file_api_auth_v1_organization_proto_enumTypes[0]
}

func (x Organization_OrganizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Organization_OrganizationType.Descriptor instead.
func (Organization_OrganizationType) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{0, 0}
}

type Organization_OrganizationStatus int32

const (
	Organization_UNSPECIFIED Organization_OrganizationStatus = 0
	Organization_active      Organization_OrganizationStatus = 1
	Organization_inactive    Organization_OrganizationStatus = 2
	Organization_banned      Organization_OrganizationStatus = 3
)

// Enum value maps for Organization_OrganizationStatus.
var (
	Organization_OrganizationStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "active",
		2: "inactive",
		3: "banned",
	}
	Organization_OrganizationStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"active":      1,
		"inactive":    2,
		"banned":      3,
	}
)

func (x Organization_OrganizationStatus) Enum() *Organization_OrganizationStatus {
	p := new(Organization_OrganizationStatus)
	*p = x
	return p
}

func (x Organization_OrganizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Organization_OrganizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_organization_proto_enumTypes[1].Descriptor()
}

func (Organization_OrganizationStatus) Type() protoreflect.EnumType {
	return &file_api_auth_v1_organization_proto_enumTypes[1]
}

func (x Organization_OrganizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Organization_OrganizationStatus.Descriptor instead.
func (Organization_OrganizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{0, 1}
}

type Organization struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	Id               string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationType Organization_OrganizationType   `protobuf:"varint,3,opt,name=organization_type,json=organizationType,proto3,enum=gh.protos.v1.Organization_OrganizationType" json:"organization_type,omitempty"`
	Email            string                          `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AdminId          string                          `protobuf:"bytes,5,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	CreatorId        string                          `protobuf:"bytes,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Status           Organization_OrganizationStatus `protobuf:"varint,7,opt,name=status,proto3,enum=gh.protos.v1.Organization_OrganizationStatus" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp          `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp          `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Currency         string                          `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetOrganizationType() Organization_OrganizationType {
	if x != nil {
		return x.OrganizationType
	}
	return Organization_UNKNOWN
}

func (x *Organization) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Organization) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *Organization) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Organization) GetStatus() Organization_OrganizationStatus {
	if x != nil {
		return x.Status
	}
	return Organization_UNSPECIFIED
}

func (x *Organization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Organization) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type OrganizationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationByIDRequest) Reset() {
	*x = OrganizationByIDRequest{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationByIDRequest) ProtoMessage() {}

func (x *OrganizationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationByIDRequest.ProtoReflect.Descriptor instead.
func (*OrganizationByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizationByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrganizationByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationByIDResponse) Reset() {
	*x = OrganizationByIDResponse{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationByIDResponse) ProtoMessage() {}

func (x *OrganizationByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationByIDResponse.ProtoReflect.Descriptor instead.
func (*OrganizationByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *OrganizationByIDResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type OrganizationByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationByOwnerRequest) Reset() {
	*x = OrganizationByOwnerRequest{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationByOwnerRequest) ProtoMessage() {}

func (x *OrganizationByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationByOwnerRequest.ProtoReflect.Descriptor instead.
func (*OrganizationByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationByOwnerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OrganizationByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationByOwnerResponse) Reset() {
	*x = OrganizationByOwnerResponse{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationByOwnerResponse) ProtoMessage() {}

func (x *OrganizationByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationByOwnerResponse.ProtoReflect.Descriptor instead.
func (*OrganizationByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *OrganizationByOwnerResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type OrganizationsForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationsForUserRequest) Reset() {
	*x = OrganizationsForUserRequest{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationsForUserRequest) ProtoMessage() {}

func (x *OrganizationsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationsForUserRequest.ProtoReflect.Descriptor instead.
func (*OrganizationsForUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OrganizationsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  []*Organization        `protobuf:"bytes,1,rep,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationsForUserResponse) Reset() {
	*x = OrganizationsForUserResponse{}
	mi := &file_api_auth_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationsForUserResponse) ProtoMessage() {}

func (x *OrganizationsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationsForUserResponse.ProtoReflect.Descriptor instead.
func (*OrganizationsForUserResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *OrganizationsForUserResponse) GetOrganization() []*Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

var File_api_auth_v1_organization_proto protoreflect.FileDescriptor

const file_api_auth_v1_organization_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/auth/v1/organization.proto\x12\fgh.protos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x04\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12X\n" +
	"\x11organization_type\x18\x03 \x01(\x0e2+.gh.protos.v1.Organization.OrganizationTypeR\x10organizationType\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x19\n" +
	"\badmin_id\x18\x05 \x01(\tR\aadminId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x06 \x01(\tR\tcreatorId\x12E\n" +
	"\x06status\x18\a \x01(\x0e2-.gh.protos.v1.Organization.OrganizationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\"=\n" +
	"\x10OrganizationType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"individual\x10\x01\x12\f\n" +
	"\bbusiness\x10\x02\"K\n" +
	"\x12OrganizationStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06active\x10\x01\x12\f\n" +
	"\binactive\x10\x02\x12\n" +
	"\n" +
	"\x06banned\x10\x03\")\n" +
	"\x17OrganizationByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x18OrganizationByIDResponse\x12>\n" +
	"\forganization\x18\x01 \x01(\v2\x1a.gh.protos.v1.OrganizationR\forganization\"5\n" +
	"\x1aOrganizationByOwnerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x1bOrganizationByOwnerResponse\x12>\n" +
	"\forganization\x18\x01 \x01(\v2\x1a.gh.protos.v1.OrganizationR\forganization\"6\n" +
	"\x1bOrganizationsForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x1cOrganizationsForUserResponse\x12>\n" +
	"\forganization\x18\x01 \x03(\v2\x1a.gh.protos.v1.OrganizationR\forganizationB\xb9\x01\n" +
	"\x10com.gh.protos.v1B\x11OrganizationProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_organization_proto_rawDescOnce sync.Once
	file_api_auth_v1_organization_proto_rawDescData []byte
)

func file_api_auth_v1_organization_proto_rawDescGZIP() []byte {
	file_api_auth_v1_organization_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_organization_proto_rawDesc), len(file_api_auth_v1_organization_proto_rawDesc)))
	})
	return file_api_auth_v1_organization_proto_rawDescData
}

var file_api_auth_v1_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_auth_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_auth_v1_organization_proto_goTypes = []any{
	(Organization_OrganizationType)(0),   // 0: gh.protos.v1.Organization.OrganizationType
	(Organization_OrganizationStatus)(0), // 1: gh.protos.v1.Organization.OrganizationStatus
	(*Organization)(nil),                 // 2: gh.protos.v1.Organization
	(*OrganizationByIDRequest)(nil),      // 3: gh.protos.v1.OrganizationByIDRequest
	(*OrganizationByIDResponse)(nil),     // 4: gh.protos.v1.OrganizationByIDResponse
	(*OrganizationByOwnerRequest)(nil),   // 5: gh.protos.v1.OrganizationByOwnerRequest
	(*OrganizationByOwnerResponse)(nil),  // 6: gh.protos.v1.OrganizationByOwnerResponse
	(*OrganizationsForUserRequest)(nil),  // 7: gh.protos.v1.OrganizationsForUserRequest
	(*OrganizationsForUserResponse)(nil), // 8: gh.protos.v1.OrganizationsForUserResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_api_auth_v1_organization_proto_depIdxs = []int32{
	0, // 0: gh.protos.v1.Organization.organization_type:type_name -> gh.protos.v1.Organization.OrganizationType
	1, // 1: gh.protos.v1.Organization.status:type_name -> gh.protos.v1.Organization.OrganizationStatus
	9, // 2: gh.protos.v1.Organization.created_at:type_name -> google.protobuf.Timestamp
	9, // 3: gh.protos.v1.Organization.updated_at:type_name -> google.protobuf.Timestamp
	2, // 4: gh.protos.v1.OrganizationByIDResponse.organization:type_name -> gh.protos.v1.Organization
	2, // 5: gh.protos.v1.OrganizationByOwnerResponse.organization:type_name -> gh.protos.v1.Organization
	2, // 6: gh.protos.v1.OrganizationsForUserResponse.organization:type_name -> gh.protos.v1.Organization
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_auth_v1_organization_proto_init() }
func file_api_auth_v1_organization_proto_init() {
	if File_api_auth_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_organization_proto_rawDesc), len(file_api_auth_v1_organization_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_organization_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_organization_proto_depIdxs,
		EnumInfos:         file_api_auth_v1_organization_proto_enumTypes,
		MessageInfos:      file_api_auth_v1_organization_proto_msgTypes,
	}.Build()
	File_api_auth_v1_organization_proto = out.File
	file_api_auth_v1_organization_proto_goTypes = nil
	file_api_auth_v1_organization_proto_depIdxs = nil
}
