// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/password_reset_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_password_reset_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_password_reset_service_proto_rawDesc = "" +
	"\n" +
	"(api/auth/v1/password_reset_service.proto\x12\fgh.protos.v1\x1a api/auth/v1/password_reset.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\x94\x02\n" +
	"\x14PasswordResetService\x12\x7f\n" +
	"\x0eForgotPassword\x12#.gh.protos.v1.ForgotPasswordRequest\x1a$.gh.protos.v1.ForgotPasswordResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/forgot-password\x12{\n" +
	"\rResetPassword\x12\".gh.protos.v1.ResetPasswordRequest\x1a#.gh.protos.v1.ResetPasswordResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/reset-passwordB\xc1\x01\n" +
	"\x10com.gh.protos.v1B\x19PasswordResetServiceProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_password_reset_service_proto_goTypes = []any{
	(*ForgotPasswordRequest)(nil),  // 0: gh.protos.v1.ForgotPasswordRequest
	(*ResetPasswordRequest)(nil),   // 1: gh.protos.v1.ResetPasswordRequest
	(*ForgotPasswordResponse)(nil), // 2: gh.protos.v1.ForgotPasswordResponse
	(*ResetPasswordResponse)(nil),  // 3: gh.protos.v1.ResetPasswordResponse
}
var file_api_auth_v1_password_reset_service_proto_depIdxs = []int32{
	0, // 0: gh.protos.v1.PasswordResetService.ForgotPassword:input_type -> gh.protos.v1.ForgotPasswordRequest
	1, // 1: gh.protos.v1.PasswordResetService.ResetPassword:input_type -> gh.protos.v1.ResetPasswordRequest
	2, // 2: gh.protos.v1.PasswordResetService.ForgotPassword:output_type -> gh.protos.v1.ForgotPasswordResponse
	3, // 3: gh.protos.v1.PasswordResetService.ResetPassword:output_type -> gh.protos.v1.ResetPasswordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_password_reset_service_proto_init() }
func file_api_auth_v1_password_reset_service_proto_init() {
	if File_api_auth_v1_password_reset_service_proto != nil {
		return
	}
	file_api_auth_v1_password_reset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_password_reset_service_proto_rawDesc), len(file_api_auth_v1_password_reset_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_password_reset_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_password_reset_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_password_reset_service_proto = out.File
	file_api_auth_v1_password_reset_service_proto_goTypes = nil
	file_api_auth_v1_password_reset_service_proto_depIdxs = nil
}
