// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/session_service.proto

package protosv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_session_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_session_service_proto_rawDesc = "" +
	"\n" +
	"!api/auth/v1/session_service.proto\x12\fgh.protos.v1\x1a\x19api/auth/v1/session.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto2\x91\x05\n" +
	"\x0eSessionService\x12Z\n" +
	"\x05Login\x12\x1a.gh.protos.v1.LoginRequest\x1a\x1b.gh.protos.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12[\n" +
	"\x06Logout\x12\x1b.gh.protos.v1.LogoutRequest\x1a\x1c.gh.protos.v1.LogoutResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/api/v1/logout\x12p\n" +
	"\vVerifyToken\x12 .gh.protos.v1.VerifyTokenRequest\x1a!.gh.protos.v1.VerifyTokenResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x14/api/v1/verify_token\x12l\n" +
	"\n" +
	"RequestOTP\x12\x1f.gh.protos.v1.RequestOTPRequest\x1a .gh.protos.v1.RequestOTPResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/request_otp\x12k\n" +
	"\tVerifyOTP\x12\x1e.gh.protos.v1.VerifyOTPRequest\x1a\x1f.gh.protos.v1.VerifyOTPResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/verify_otp\x12y\n" +
	"\x0eUnblockSession\x12#.gh.protos.v1.UnblockSessionRequest\x1a$.gh.protos.v1.UnblockSessionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/biblopassB\xbb\x01\n" +
	"\x10com.gh.protos.v1B\x13SessionServiceProtoP\x01Z@github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var file_api_auth_v1_session_service_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: gh.protos.v1.LoginRequest
	(*LogoutRequest)(nil),          // 1: gh.protos.v1.LogoutRequest
	(*VerifyTokenRequest)(nil),     // 2: gh.protos.v1.VerifyTokenRequest
	(*RequestOTPRequest)(nil),      // 3: gh.protos.v1.RequestOTPRequest
	(*VerifyOTPRequest)(nil),       // 4: gh.protos.v1.VerifyOTPRequest
	(*UnblockSessionRequest)(nil),  // 5: gh.protos.v1.UnblockSessionRequest
	(*LoginResponse)(nil),          // 6: gh.protos.v1.LoginResponse
	(*LogoutResponse)(nil),         // 7: gh.protos.v1.LogoutResponse
	(*VerifyTokenResponse)(nil),    // 8: gh.protos.v1.VerifyTokenResponse
	(*RequestOTPResponse)(nil),     // 9: gh.protos.v1.RequestOTPResponse
	(*VerifyOTPResponse)(nil),      // 10: gh.protos.v1.VerifyOTPResponse
	(*UnblockSessionResponse)(nil), // 11: gh.protos.v1.UnblockSessionResponse
}
var file_api_auth_v1_session_service_proto_depIdxs = []int32{
	0,  // 0: gh.protos.v1.SessionService.Login:input_type -> gh.protos.v1.LoginRequest
	1,  // 1: gh.protos.v1.SessionService.Logout:input_type -> gh.protos.v1.LogoutRequest
	2,  // 2: gh.protos.v1.SessionService.VerifyToken:input_type -> gh.protos.v1.VerifyTokenRequest
	3,  // 3: gh.protos.v1.SessionService.RequestOTP:input_type -> gh.protos.v1.RequestOTPRequest
	4,  // 4: gh.protos.v1.SessionService.VerifyOTP:input_type -> gh.protos.v1.VerifyOTPRequest
	5,  // 5: gh.protos.v1.SessionService.UnblockSession:input_type -> gh.protos.v1.UnblockSessionRequest
	6,  // 6: gh.protos.v1.SessionService.Login:output_type -> gh.protos.v1.LoginResponse
	7,  // 7: gh.protos.v1.SessionService.Logout:output_type -> gh.protos.v1.LogoutResponse
	8,  // 8: gh.protos.v1.SessionService.VerifyToken:output_type -> gh.protos.v1.VerifyTokenResponse
	9,  // 9: gh.protos.v1.SessionService.RequestOTP:output_type -> gh.protos.v1.RequestOTPResponse
	10, // 10: gh.protos.v1.SessionService.VerifyOTP:output_type -> gh.protos.v1.VerifyOTPResponse
	11, // 11: gh.protos.v1.SessionService.UnblockSession:output_type -> gh.protos.v1.UnblockSessionResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_session_service_proto_init() }
func file_api_auth_v1_session_service_proto_init() {
	if File_api_auth_v1_session_service_proto != nil {
		return
	}
	file_api_auth_v1_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_session_service_proto_rawDesc), len(file_api_auth_v1_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_session_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_session_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_session_service_proto = out.File
	file_api_auth_v1_session_service_proto_goTypes = nil
	file_api_auth_v1_session_service_proto_depIdxs = nil
}
