// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth/v1/user.proto

package protosv1

import (
	v1 "github.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName               string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber             *v1.PhoneNumber        `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Username                string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Status                  AuthStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=gh.protos.v1.AuthStatus" json:"status,omitempty"`
	IsAdmin                 bool                   `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Bio                     string                 `protobuf:"bytes,9,opt,name=bio,proto3" json:"bio,omitempty"`
	Filename                string                 `protobuf:"bytes,10,opt,name=filename,proto3" json:"filename,omitempty"`
	DateOfBirth             *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PinSet                  bool                   `protobuf:"varint,12,opt,name=pin_set,json=pinSet,proto3" json:"pin_set,omitempty"`
	EmailVerified           bool                   `protobuf:"varint,13,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PhoneVerified           bool                   `protobuf:"varint,14,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	EmailActivationAttempts float32                `protobuf:"fixed32,15,opt,name=email_activation_attempts,json=emailActivationAttempts,proto3" json:"email_activation_attempts,omitempty"`
	PhoneActivationAttempts float32                `protobuf:"fixed32,16,opt,name=phone_activation_attempts,json=phoneActivationAttempts,proto3" json:"phone_activation_attempts,omitempty"`
	OrganizationId          string                 `protobuf:"bytes,17,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_auth_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() *v1.PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetStatus() AuthStatus {
	if x != nil {
		return x.Status
	}
	return AuthStatus_UNKNOWN
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *User) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *User) GetPinSet() bool {
	if x != nil {
		return x.PinSet
	}
	return false
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *User) GetEmailActivationAttempts() float32 {
	if x != nil {
		return x.EmailActivationAttempts
	}
	return 0
}

func (x *User) GetPhoneActivationAttempts() float32 {
	if x != nil {
		return x.PhoneActivationAttempts
	}
	return 0
}

func (x *User) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChangePasswordRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword          string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Password             string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string                 `protobuf:"bytes,4,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ChangePasswordRequest) GetPasswordConfirmation() string {
	if x != nil {
		return x.PasswordConfirmation
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePasswordResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName            string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DialCode             string                 `protobuf:"bytes,4,opt,name=dial_code,json=dialCode,proto3" json:"dial_code,omitempty"`
	Number               string                 `protobuf:"bytes,5,opt,name=number,proto3" json:"number,omitempty"`
	Email                string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Filename             string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	Bio                  string                 `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	DateOfBirth          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PreferredTwoFaMethod string                 `protobuf:"bytes,10,opt,name=preferred_two_fa_method,json=preferredTwoFaMethod,proto3" json:"preferred_two_fa_method,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetDialCode() string {
	if x != nil {
		return x.DialCode
	}
	return ""
}

func (x *UpdateUserRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateUserRequest) GetPreferredTwoFaMethod() string {
	if x != nil {
		return x.PreferredTwoFaMethod
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserByIDRequest) Reset() {
	*x = UserByIDRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserByIDRequest) ProtoMessage() {}

func (x *UserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserByIDRequest.ProtoReflect.Descriptor instead.
func (*UserByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserByIDResponse) Reset() {
	*x = UserByIDResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserByIDResponse) ProtoMessage() {}

func (x *UserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserByIDResponse.ProtoReflect.Descriptor instead.
func (*UserByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserByUsernameRequest) Reset() {
	*x = UserByUsernameRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserByUsernameRequest) ProtoMessage() {}

func (x *UserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*UserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserByUsernameResponse) Reset() {
	*x = UserByUsernameResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserByUsernameResponse) ProtoMessage() {}

func (x *UserByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserByUsernameResponse.ProtoReflect.Descriptor instead.
func (*UserByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserByUsernameResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterUserRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FirstName            string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DialCode             string                 `protobuf:"bytes,5,opt,name=dial_code,json=dialCode,proto3" json:"dial_code,omitempty"`
	Number               string                 `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	Password             string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string                 `protobuf:"bytes,8,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetDialCode() string {
	if x != nil {
		return x.DialCode
	}
	return ""
}

func (x *RegisterUserRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetPasswordConfirmation() string {
	if x != nil {
		return x.PasswordConfirmation
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SendEmailCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeRequest) Reset() {
	*x = SendEmailCodeRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeRequest) ProtoMessage() {}

func (x *SendEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*SendEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *SendEmailCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendEmailCodeRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type SendEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeResponse) Reset() {
	*x = SendEmailCodeResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeResponse) ProtoMessage() {}

func (x *SendEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*SendEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *SendEmailCodeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SendPhoneCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPhoneCodeRequest) Reset() {
	*x = SendPhoneCodeRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPhoneCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneCodeRequest) ProtoMessage() {}

func (x *SendPhoneCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneCodeRequest.ProtoReflect.Descriptor instead.
func (*SendPhoneCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *SendPhoneCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SendPhoneCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPhoneCodeResponse) Reset() {
	*x = SendPhoneCodeResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPhoneCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneCodeResponse) ProtoMessage() {}

func (x *SendPhoneCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneCodeResponse.ProtoReflect.Descriptor instead.
func (*SendPhoneCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *SendPhoneCodeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ActivateUserEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserEmailRequest) Reset() {
	*x = ActivateUserEmailRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserEmailRequest) ProtoMessage() {}

func (x *ActivateUserEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserEmailRequest.ProtoReflect.Descriptor instead.
func (*ActivateUserEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateUserEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivateUserEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ActivateUserEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sucess        bool                   `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserEmailResponse) Reset() {
	*x = ActivateUserEmailResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserEmailResponse) ProtoMessage() {}

func (x *ActivateUserEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserEmailResponse.ProtoReflect.Descriptor instead.
func (*ActivateUserEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *ActivateUserEmailResponse) GetSucess() bool {
	if x != nil {
		return x.Sucess
	}
	return false
}

func (x *ActivateUserEmailResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ActivateUserPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserPhoneRequest) Reset() {
	*x = ActivateUserPhoneRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserPhoneRequest) ProtoMessage() {}

func (x *ActivateUserPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserPhoneRequest.ProtoReflect.Descriptor instead.
func (*ActivateUserPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *ActivateUserPhoneRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivateUserPhoneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ActivateUserPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sucess        bool                   `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserPhoneResponse) Reset() {
	*x = ActivateUserPhoneResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserPhoneResponse) ProtoMessage() {}

func (x *ActivateUserPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserPhoneResponse.ProtoReflect.Descriptor instead.
func (*ActivateUserPhoneResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *ActivateUserPhoneResponse) GetSucess() bool {
	if x != nil {
		return x.Sucess
	}
	return false
}

func (x *ActivateUserPhoneResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AccountUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountUsersRequest) Reset() {
	*x = AccountUsersRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUsersRequest) ProtoMessage() {}

func (x *AccountUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUsersRequest.ProtoReflect.Descriptor instead.
func (*AccountUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *AccountUsersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type AccountUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountUsersResponse) Reset() {
	*x = AccountUsersResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUsersResponse) ProtoMessage() {}

func (x *AccountUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUsersResponse.ProtoReflect.Descriptor instead.
func (*AccountUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *AccountUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ApproversForAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproversForAccountRequest) Reset() {
	*x = ApproversForAccountRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproversForAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproversForAccountRequest) ProtoMessage() {}

func (x *ApproversForAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproversForAccountRequest.ProtoReflect.Descriptor instead.
func (*ApproversForAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *ApproversForAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ApproversForAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproversForAccountResponse) Reset() {
	*x = ApproversForAccountResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproversForAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproversForAccountResponse) ProtoMessage() {}

func (x *ApproversForAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproversForAccountResponse.ProtoReflect.Descriptor instead.
func (*ApproversForAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *ApproversForAccountResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ValidateApproverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApproverRequest) Reset() {
	*x = ValidateApproverRequest{}
	mi := &file_api_auth_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApproverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApproverRequest) ProtoMessage() {}

func (x *ValidateApproverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApproverRequest.ProtoReflect.Descriptor instead.
func (*ValidateApproverRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *ValidateApproverRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateApproverRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateApproverRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ValidateApproverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApproverResponse) Reset() {
	*x = ValidateApproverResponse{}
	mi := &file_api_auth_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApproverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApproverResponse) ProtoMessage() {}

func (x *ValidateApproverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApproverResponse.ProtoReflect.Descriptor instead.
func (*ValidateApproverResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_user_proto_rawDescGZIP(), []int{26}
}

func (x *ValidateApproverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_auth_v1_user_proto protoreflect.FileDescriptor

const file_api_auth_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/auth/v1/user.proto\x12\fgh.protos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a api/common/v1/phone_number.proto\x1a\x1dapi/auth/v1/auth_status.proto\"\xfb\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12<\n" +
	"\fphone_number\x18\x05 \x01(\v2\x19.gh.common.v1.PhoneNumberR\vphoneNumber\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.gh.protos.v1.AuthStatusR\x06status\x12\x19\n" +
	"\bis_admin\x18\b \x01(\bR\aisAdmin\x12\x10\n" +
	"\x03bio\x18\t \x01(\tR\x03bio\x12\x1a\n" +
	"\bfilename\x18\n" +
	" \x01(\tR\bfilename\x12>\n" +
	"\rdate_of_birth\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x17\n" +
	"\apin_set\x18\f \x01(\bR\x06pinSet\x12%\n" +
	"\x0eemail_verified\x18\r \x01(\bR\remailVerified\x12%\n" +
	"\x0ephone_verified\x18\x0e \x01(\bR\rphoneVerified\x12:\n" +
	"\x19email_activation_attempts\x18\x0f \x01(\x02R\x17emailActivationAttempts\x12:\n" +
	"\x19phone_activation_attempts\x18\x10 \x01(\x02R\x17phoneActivationAttempts\x12'\n" +
	"\x0forganization_id\x18\x11 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa4\x01\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x123\n" +
	"\x15password_confirmation\x18\x04 \x01(\tR\x14passwordConfirmation\"@\n" +
	"\x16ChangePasswordResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"\xd8\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1b\n" +
	"\tdial_code\x18\x04 \x01(\tR\bdialCode\x12\x16\n" +
	"\x06number\x18\x05 \x01(\tR\x06number\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x10\n" +
	"\x03bio\x18\b \x01(\tR\x03bio\x12>\n" +
	"\rdate_of_birth\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x125\n" +
	"\x17preferred_two_fa_method\x18\n" +
	" \x01(\tR\x14preferredTwoFaMethod\"<\n" +
	"\x12UpdateUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"*\n" +
	"\x0fUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x10UserByIDResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"3\n" +
	"\x15UserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"@\n" +
	"\x16UserByUsernameResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"\x89\x02\n" +
	"\x13RegisterUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1b\n" +
	"\tdial_code\x18\x05 \x01(\tR\bdialCode\x12\x16\n" +
	"\x06number\x18\x06 \x01(\tR\x06number\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x123\n" +
	"\x15password_confirmation\x18\b \x01(\tR\x14passwordConfirmation\">\n" +
	"\x14RegisterUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"J\n" +
	"\x14SendEmailCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"?\n" +
	"\x15SendEmailCodeResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"/\n" +
	"\x14SendPhoneCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"?\n" +
	"\x15SendPhoneCodeResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"G\n" +
	"\x18ActivateUserEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"V\n" +
	"\x19ActivateUserEmailResponse\x12\x16\n" +
	"\x06sucess\x18\x01 \x01(\bR\x06sucess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"G\n" +
	"\x18ActivateUserPhoneRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"V\n" +
	"\x19ActivateUserPhoneResponse\x12\x16\n" +
	"\x06sucess\x18\x01 \x01(\bR\x06sucess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"<\n" +
	"\x12DeleteUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.gh.protos.v1.UserR\x04user\"4\n" +
	"\x13AccountUsersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"@\n" +
	"\x14AccountUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.gh.protos.v1.UserR\x05users\";\n" +
	"\x1aApproversForAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"G\n" +
	"\x1bApproversForAccountResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.gh.protos.v1.UserR\x05users\"m\n" +
	"\x17ValidateApproverRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"4\n" +
	"\x18ValidateApproverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\xbc\x01\n" +
	"\x10com.gh.protos.v1B\tUserProtoP\x01ZKgithub.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/auth/v1;protosv1\xa2\x02\x03GPX\xaa\x02\fGh.Protos.V1\xca\x02\fGh\\Protos\\V1\xe2\x02\x18Gh\\Protos\\V1\\GPBMetadata\xea\x02\x0eGh::Protos::V1b\x06proto3"

var (
	file_api_auth_v1_user_proto_rawDescOnce sync.Once
	file_api_auth_v1_user_proto_rawDescData []byte
)

func file_api_auth_v1_user_proto_rawDescGZIP() []byte {
	file_api_auth_v1_user_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_user_proto_rawDesc), len(file_api_auth_v1_user_proto_rawDesc)))
	})
	return file_api_auth_v1_user_proto_rawDescData
}

var file_api_auth_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_auth_v1_user_proto_goTypes = []any{
	(*User)(nil),                        // 0: gh.protos.v1.User
	(*ChangePasswordRequest)(nil),       // 1: gh.protos.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),      // 2: gh.protos.v1.ChangePasswordResponse
	(*UpdateUserRequest)(nil),           // 3: gh.protos.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),          // 4: gh.protos.v1.UpdateUserResponse
	(*UserByIDRequest)(nil),             // 5: gh.protos.v1.UserByIDRequest
	(*UserByIDResponse)(nil),            // 6: gh.protos.v1.UserByIDResponse
	(*UserByUsernameRequest)(nil),       // 7: gh.protos.v1.UserByUsernameRequest
	(*UserByUsernameResponse)(nil),      // 8: gh.protos.v1.UserByUsernameResponse
	(*RegisterUserRequest)(nil),         // 9: gh.protos.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),        // 10: gh.protos.v1.RegisterUserResponse
	(*SendEmailCodeRequest)(nil),        // 11: gh.protos.v1.SendEmailCodeRequest
	(*SendEmailCodeResponse)(nil),       // 12: gh.protos.v1.SendEmailCodeResponse
	(*SendPhoneCodeRequest)(nil),        // 13: gh.protos.v1.SendPhoneCodeRequest
	(*SendPhoneCodeResponse)(nil),       // 14: gh.protos.v1.SendPhoneCodeResponse
	(*ActivateUserEmailRequest)(nil),    // 15: gh.protos.v1.ActivateUserEmailRequest
	(*ActivateUserEmailResponse)(nil),   // 16: gh.protos.v1.ActivateUserEmailResponse
	(*ActivateUserPhoneRequest)(nil),    // 17: gh.protos.v1.ActivateUserPhoneRequest
	(*ActivateUserPhoneResponse)(nil),   // 18: gh.protos.v1.ActivateUserPhoneResponse
	(*DeleteUserRequest)(nil),           // 19: gh.protos.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),          // 20: gh.protos.v1.DeleteUserResponse
	(*AccountUsersRequest)(nil),         // 21: gh.protos.v1.AccountUsersRequest
	(*AccountUsersResponse)(nil),        // 22: gh.protos.v1.AccountUsersResponse
	(*ApproversForAccountRequest)(nil),  // 23: gh.protos.v1.ApproversForAccountRequest
	(*ApproversForAccountResponse)(nil), // 24: gh.protos.v1.ApproversForAccountResponse
	(*ValidateApproverRequest)(nil),     // 25: gh.protos.v1.ValidateApproverRequest
	(*ValidateApproverResponse)(nil),    // 26: gh.protos.v1.ValidateApproverResponse
	(*v1.PhoneNumber)(nil),              // 27: gh.common.v1.PhoneNumber
	(AuthStatus)(0),                     // 28: gh.protos.v1.AuthStatus
	(*timestamppb.Timestamp)(nil),       // 29: google.protobuf.Timestamp
}
var file_api_auth_v1_user_proto_depIdxs = []int32{
	27, // 0: gh.protos.v1.User.phone_number:type_name -> gh.common.v1.PhoneNumber
	28, // 1: gh.protos.v1.User.status:type_name -> gh.protos.v1.AuthStatus
	29, // 2: gh.protos.v1.User.date_of_birth:type_name -> google.protobuf.Timestamp
	29, // 3: gh.protos.v1.User.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: gh.protos.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: gh.protos.v1.ChangePasswordResponse.user:type_name -> gh.protos.v1.User
	29, // 6: gh.protos.v1.UpdateUserRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	0,  // 7: gh.protos.v1.UpdateUserResponse.user:type_name -> gh.protos.v1.User
	0,  // 8: gh.protos.v1.UserByIDResponse.user:type_name -> gh.protos.v1.User
	0,  // 9: gh.protos.v1.UserByUsernameResponse.user:type_name -> gh.protos.v1.User
	0,  // 10: gh.protos.v1.RegisterUserResponse.user:type_name -> gh.protos.v1.User
	0,  // 11: gh.protos.v1.SendEmailCodeResponse.user:type_name -> gh.protos.v1.User
	0,  // 12: gh.protos.v1.SendPhoneCodeResponse.user:type_name -> gh.protos.v1.User
	0,  // 13: gh.protos.v1.DeleteUserResponse.user:type_name -> gh.protos.v1.User
	0,  // 14: gh.protos.v1.AccountUsersResponse.users:type_name -> gh.protos.v1.User
	0,  // 15: gh.protos.v1.ApproversForAccountResponse.users:type_name -> gh.protos.v1.User
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_auth_v1_user_proto_init() }
func file_api_auth_v1_user_proto_init() {
	if File_api_auth_v1_user_proto != nil {
		return
	}
	file_api_auth_v1_auth_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_user_proto_rawDesc), len(file_api_auth_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_user_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_user_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_user_proto_msgTypes,
	}.Build()
	File_api_auth_v1_user_proto = out.File
	file_api_auth_v1_user_proto_goTypes = nil
	file_api_auth_v1_user_proto_depIdxs = nil
}
