// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/common/v1/filter.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterQuery struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccountId           string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrganizationId      string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page                int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Per                 int64                  `protobuf:"varint,4,opt,name=per,proto3" json:"per,omitempty"`
	Term                string                 `protobuf:"bytes,5,opt,name=term,proto3" json:"term,omitempty"`
	UserId              string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Username            string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Number              string                 `protobuf:"bytes,9,opt,name=number,proto3" json:"number,omitempty"`
	Email               string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	TransactionCategory string                 `protobuf:"bytes,11,opt,name=transaction_category,json=transactionCategory,proto3" json:"transaction_category,omitempty"`
	WalletType          string                 `protobuf:"bytes,12,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FilterQuery) Reset() {
	*x = FilterQuery{}
	mi := &file_api_common_v1_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterQuery) ProtoMessage() {}

func (x *FilterQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterQuery.ProtoReflect.Descriptor instead.
func (*FilterQuery) Descriptor() ([]byte, []int) {
	return file_api_common_v1_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterQuery) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FilterQuery) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *FilterQuery) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FilterQuery) GetPer() int64 {
	if x != nil {
		return x.Per
	}
	return 0
}

func (x *FilterQuery) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *FilterQuery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FilterQuery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FilterQuery) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FilterQuery) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *FilterQuery) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FilterQuery) GetTransactionCategory() string {
	if x != nil {
		return x.TransactionCategory
	}
	return ""
}

func (x *FilterQuery) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

var File_api_common_v1_filter_proto protoreflect.FileDescriptor

const file_api_common_v1_filter_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/filter.proto\x12\fgh.common.v1\"\xde\x02\n" +
	"\vFilterQuery\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x10\n" +
	"\x03per\x18\x04 \x01(\x03R\x03per\x12\x12\n" +
	"\x04term\x18\x05 \x01(\tR\x04term\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x16\n" +
	"\x06number\x18\t \x01(\tR\x06number\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x121\n" +
	"\x14transaction_category\x18\v \x01(\tR\x13transactionCategory\x12\x1f\n" +
	"\vwallet_type\x18\f \x01(\tR\n" +
	"walletTypeB\xc0\x01\n" +
	"\x10com.gh.common.v1B\vFilterProtoP\x01ZMgithub.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/common/v1;commonv1\xa2\x02\x03GCX\xaa\x02\fGh.Common.V1\xca\x02\fGh\\Common\\V1\xe2\x02\x18Gh\\Common\\V1\\GPBMetadata\xea\x02\x0eGh::Common::V1b\x06proto3"

var (
	file_api_common_v1_filter_proto_rawDescOnce sync.Once
	file_api_common_v1_filter_proto_rawDescData []byte
)

func file_api_common_v1_filter_proto_rawDescGZIP() []byte {
	file_api_common_v1_filter_proto_rawDescOnce.Do(func() {
		file_api_common_v1_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_filter_proto_rawDesc), len(file_api_common_v1_filter_proto_rawDesc)))
	})
	return file_api_common_v1_filter_proto_rawDescData
}

var file_api_common_v1_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_v1_filter_proto_goTypes = []any{
	(*FilterQuery)(nil), // 0: gh.common.v1.FilterQuery
}
var file_api_common_v1_filter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_v1_filter_proto_init() }
func file_api_common_v1_filter_proto_init() {
	if File_api_common_v1_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_filter_proto_rawDesc), len(file_api_common_v1_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_filter_proto_goTypes,
		DependencyIndexes: file_api_common_v1_filter_proto_depIdxs,
		MessageInfos:      file_api_common_v1_filter_proto_msgTypes,
	}.Build()
	File_api_common_v1_filter_proto = out.File
	file_api_common_v1_filter_proto_goTypes = nil
	file_api_common_v1_filter_proto_depIdxs = nil
}
