// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/common/v1/image.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ImageType     string                 `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_api_common_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageInfo) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *ImageInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadImageRequest_Info
	//	*UploadImageRequest_ChunkData
	Data          isUploadImageRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_api_common_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_api_common_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageRequest) GetData() isUploadImageRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetInfo() *ImageInfo {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadImageRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadImageRequest_Data interface {
	isUploadImageRequest_Data()
}

type UploadImageRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadImageRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadImageRequest_Info) isUploadImageRequest_Data() {}

func (*UploadImageRequest_ChunkData) isUploadImageRequest_Data() {}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_api_common_v1_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_api_common_v1_image_proto_rawDescGZIP(), []int{2}
}

func (x *UploadImageResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UploadImageResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_api_common_v1_image_proto protoreflect.FileDescriptor

const file_api_common_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x19api/common/v1/image.proto\x12\fgh.common.v1\"K\n" +
	"\tImageInfo\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\x03R\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"image_type\x18\x02 \x01(\tR\timageType\"l\n" +
	"\x12UploadImageRequest\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x17.gh.common.v1.ImageInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"K\n" +
	"\x13UploadImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03urlB\xbf\x01\n" +
	"\x10com.gh.common.v1B\n" +
	"ImageProtoP\x01ZMgithub.com/github.com/PAY-HERO-CONSULTING/gh-protos/pb/api/common/v1;commonv1\xa2\x02\x03GCX\xaa\x02\fGh.Common.V1\xca\x02\fGh\\Common\\V1\xe2\x02\x18Gh\\Common\\V1\\GPBMetadata\xea\x02\x0eGh::Common::V1b\x06proto3"

var (
	file_api_common_v1_image_proto_rawDescOnce sync.Once
	file_api_common_v1_image_proto_rawDescData []byte
)

func file_api_common_v1_image_proto_rawDescGZIP() []byte {
	file_api_common_v1_image_proto_rawDescOnce.Do(func() {
		file_api_common_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_image_proto_rawDesc), len(file_api_common_v1_image_proto_rawDesc)))
	})
	return file_api_common_v1_image_proto_rawDescData
}

var file_api_common_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_common_v1_image_proto_goTypes = []any{
	(*ImageInfo)(nil),           // 0: gh.common.v1.ImageInfo
	(*UploadImageRequest)(nil),  // 1: gh.common.v1.UploadImageRequest
	(*UploadImageResponse)(nil), // 2: gh.common.v1.UploadImageResponse
}
var file_api_common_v1_image_proto_depIdxs = []int32{
	0, // 0: gh.common.v1.UploadImageRequest.info:type_name -> gh.common.v1.ImageInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_common_v1_image_proto_init() }
func file_api_common_v1_image_proto_init() {
	if File_api_common_v1_image_proto != nil {
		return
	}
	file_api_common_v1_image_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadImageRequest_Info)(nil),
		(*UploadImageRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_image_proto_rawDesc), len(file_api_common_v1_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_image_proto_goTypes,
		DependencyIndexes: file_api_common_v1_image_proto_depIdxs,
		MessageInfos:      file_api_common_v1_image_proto_msgTypes,
	}.Build()
	File_api_common_v1_image_proto = out.File
	file_api_common_v1_image_proto_goTypes = nil
	file_api_common_v1_image_proto_depIdxs = nil
}
