// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/common/v1/phone_number.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialCode      string                 `protobuf:"bytes,1,opt,name=dial_code,json=dialCode,proto3" json:"dial_code,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_api_common_v1_phone_number_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_phone_number_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_api_common_v1_phone_number_proto_rawDescGZIP(), []int{0}
}

func (x *PhoneNumber) GetDialCode() string {
	if x != nil {
		return x.DialCode
	}
	return ""
}

func (x *PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_api_common_v1_phone_number_proto protoreflect.FileDescriptor

const file_api_common_v1_phone_number_proto_rawDesc = "" +
	"\n" +
	" api/common/v1/phone_number.proto\x12\fgh.common.v1\"B\n" +
	"\vPhoneNumber\x12\x1b\n" +
	"\tdial_code\x18\x01 \x01(\tR\bdialCode\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06numberB\xba\x01\n" +
	"\x10com.gh.common.v1B\x10PhoneNumberProtoP\x01ZBgithub.com/PAY-HERO-CONSULTING/gh-protos/pb/api/common/v1;commonv1\xa2\x02\x03GCX\xaa\x02\fGh.Common.V1\xca\x02\fGh\\Common\\V1\xe2\x02\x18Gh\\Common\\V1\\GPBMetadata\xea\x02\x0eGh::Common::V1b\x06proto3"

var (
	file_api_common_v1_phone_number_proto_rawDescOnce sync.Once
	file_api_common_v1_phone_number_proto_rawDescData []byte
)

func file_api_common_v1_phone_number_proto_rawDescGZIP() []byte {
	file_api_common_v1_phone_number_proto_rawDescOnce.Do(func() {
		file_api_common_v1_phone_number_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_phone_number_proto_rawDesc), len(file_api_common_v1_phone_number_proto_rawDesc)))
	})
	return file_api_common_v1_phone_number_proto_rawDescData
}

var file_api_common_v1_phone_number_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_v1_phone_number_proto_goTypes = []any{
	(*PhoneNumber)(nil), // 0: gh.common.v1.PhoneNumber
}
var file_api_common_v1_phone_number_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_v1_phone_number_proto_init() }
func file_api_common_v1_phone_number_proto_init() {
	if File_api_common_v1_phone_number_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_phone_number_proto_rawDesc), len(file_api_common_v1_phone_number_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_phone_number_proto_goTypes,
		DependencyIndexes: file_api_common_v1_phone_number_proto_depIdxs,
		MessageInfos:      file_api_common_v1_phone_number_proto_msgTypes,
	}.Build()
	File_api_common_v1_phone_number_proto = out.File
	file_api_common_v1_phone_number_proto_goTypes = nil
	file_api_common_v1_phone_number_proto_depIdxs = nil
}
