syntax = "proto3";

package gh.protos.v1;

import "api/auth/v1/password_reset.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";

option go_package = "pb/api/auth/v1";

service PasswordResetService {
  rpc ForgotPassword(ForgotPasswordRequest) returns (ForgotPasswordResponse) {
    option (google.api.http) = {
        post : "/api/v1/forgot-password"
        body : "*"
    };
  }

  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse) {
    option (google.api.http) = {
        post : "/api/v1/reset-password"
        body : "*"
    };
  }
}
